-- Catálogo global idempotente. No crea tenants, usuarios, profiles, empleados ni secretos.
begin;
insert into public.permisos(codigo,nombre,modulo,activo) values
('portal.acceder','Acceder al portal','portal',true),('portal.ver_dashboard','Ver dashboard','portal',true),
('perfil.ver_propio','Ver perfil propio','perfil',true),('perfil.editar_propio','Editar perfil propio','perfil',true),
('empleados.ver_propio','Ver empleado propio','empleados',true),('empleados.ver_departamento','Ver empleados del departamento','empleados',true),('empleados.ver_todos','Ver todos los empleados','empleados',true),('empleados.crear','Crear empleados','empleados',true),('empleados.editar','Editar empleados','empleados',true),('empleados.desactivar','Desactivar empleados','empleados',true),
('asistencia.ver_propia','Ver asistencia propia','asistencia',true),('asistencia.ver_departamento','Ver asistencia del departamento','asistencia',true),('asistencia.ver_todas','Ver toda la asistencia','asistencia',true),('asistencia.registrar_propia','Registrar asistencia propia','asistencia',true),('asistencia.corregir','Corregir asistencia','asistencia',true),
('horarios.ver_propio','Ver horario propio','horarios',true),('horarios.ver_todos','Ver todos los horarios','horarios',true),('horarios.administrar','Administrar horarios','horarios',true),
('nomina.ver_propia','Ver nómina propia','nomina',true),('nomina.ver_todas','Ver todas las nóminas','nomina',true),('nomina.procesar','Procesar nómina','nomina',true),('nomina.aprobar','Aprobar nómina','nomina',true),('nomina.descargar','Descargar nómina','nomina',true),
('nomina.ver','Ver módulo de nómina','nomina',true),('nomina.generar','Generar y recalcular nómina','nomina',true),('nomina.editar','Editar nómina en revisión','nomina',true),('nomina.cerrar','Cerrar nómina','nomina',true),('nomina.anular','Anular nómina','nomina',true),('nomina.exportar','Exportar nómina','nomina',true),('nomina.prestamos','Administrar préstamos de nómina','nomina',true),('nomina.creditos','Administrar créditos de nómina','nomina',true),('nomina.descuentos','Administrar descuentos de nómina','nomina',true),
('reportes.ver_personales','Ver reportes personales','reportes',true),('reportes.ver_departamento','Ver reportes del departamento','reportes',true),('reportes.ver_globales','Ver reportes globales','reportes',true),('reportes.exportar','Exportar reportes','reportes',true),
('usuarios.administrar','Administrar usuarios','administracion',true),('roles.administrar','Administrar roles','administracion',true),('permisos.administrar','Administrar permisos','administracion',true),('configuracion.administrar','Administrar configuración','administracion',true)
on conflict(codigo) do update set nombre=excluded.nombre,modulo=excluded.modulo,activo=excluded.activo;
commit;
