import { getSupabaseClient } from '../../infrastructure/supabase/client';

export type EmployeeStatus = 'activo'|'pendiente'|'licencia'|'suspendido'|'desvinculado';
export interface EmployeeRecord {id:string;code:string;name:string;cedula:string;email:string;phone:string;startDate:string;status:EmployeeStatus;active:boolean;salary:number|null;payType:string;branchId:string;branchName:string;departmentId:string;departmentName:string;positionId:string;positionName:string;hasPin:boolean;fingerprintReady:boolean;fingerprintRegisteredAt:string;fingerprintDevice:string}
export interface EmployeeCatalogs {branches:{id:string;name:string}[];departments:{id:string;name:string;branch_id:string|null}[];positions:{id:string;name:string;department_id:string|null}[]}
export interface EmployeeInput {id?:string;code:string;name:string;cedula?:string;email?:string;phone?:string;startDate?:string;status:EmployeeStatus;active:boolean;salary?:number|null;payType?:string;branchId?:string;departmentId?:string;positionId?:string;pin?:string}

type EmployeeRow={id:string;codigo_empleado:string;nombre_completo:string;cedula:string|null;correo:string|null;telefono:string|null;fecha_ingreso:string|null;estado_laboral:EmployeeStatus;activo:boolean;salario:number|null;tipo_pago:string|null;sucursal_id:string|null;departamento_id:string|null;puesto_id:string|null;pin_hash:string|null;branches:{name:string}|{name:string}[]|null;departments:{name:string}|{name:string}[]|null;positions:{name:string}|{name:string}[]|null};
const related=(value:{name:string}|{name:string}[]|null)=>Array.isArray(value)?value[0]?.name??'':value?.name??'';
const map=(row:EmployeeRow):EmployeeRecord=>({id:row.id,code:row.codigo_empleado,name:row.nombre_completo,cedula:row.cedula??'',email:row.correo??'',phone:row.telefono??'',startDate:row.fecha_ingreso??'',status:row.estado_laboral,active:row.activo,salary:row.salario,payType:row.tipo_pago??'',branchId:row.sucursal_id??'',branchName:related(row.branches),departmentId:row.departamento_id??'',departmentName:related(row.departments),positionId:row.puesto_id??'',positionName:related(row.positions),hasPin:Boolean(row.pin_hash),fingerprintReady:false,fingerprintRegisteredAt:'',fingerprintDevice:''});
const invoke=async<T>(body:Record<string,unknown>)=>{const{data,error}=await getSupabaseClient().functions.invoke('employee-management',{body});if(data?.error)throw new Error(data.error);if(error)throw error;return data as T};
type BiometricState={empleado_id:string;registrada:boolean;registrado_at:string|null;dispositivo_origen:string|null};
const withBiometrics=async(items:EmployeeRecord[])=>{const{data,error}=await getSupabaseClient().rpc('listar_estados_biometricos_empleados');if(error){if(error.code==='PGRST202')return items;throw error}const states=new Map(((data??[])as BiometricState[]).map(state=>[state.empleado_id,state]));return items.map(item=>{const state=states.get(item.id);return{...item,fingerprintReady:state?.registrada===true,fingerprintRegisteredAt:state?.registrado_at??'',fingerprintDevice:state?.dispositivo_origen??''}})};

export const employeeService={
  async list(){const{data,error}=await getSupabaseClient().from('empleados').select('id,codigo_empleado,nombre_completo,cedula,correo,telefono,fecha_ingreso,estado_laboral,activo,salario,tipo_pago,sucursal_id,departamento_id,puesto_id,pin_hash,branches!empleados_sucursal_misma_empresa_fk(name),departments!empleados_departamento_misma_empresa_fk(name),positions!empleados_puesto_misma_empresa_fk(name)').order('nombre_completo');if(error)throw error;return withBiometrics((data??[]).map(row=>map(row as unknown as EmployeeRow)))},
  async get(id:string){const{data,error}=await getSupabaseClient().from('empleados').select('id,codigo_empleado,nombre_completo,cedula,correo,telefono,fecha_ingreso,estado_laboral,activo,salario,tipo_pago,sucursal_id,departamento_id,puesto_id,pin_hash,branches!empleados_sucursal_misma_empresa_fk(name),departments!empleados_departamento_misma_empresa_fk(name),positions!empleados_puesto_misma_empresa_fk(name)').eq('id',id).maybeSingle();if(error)throw error;if(!data)return null;return(await withBiometrics([map(data as unknown as EmployeeRow)]))[0]??null},
  async catalogs():Promise<EmployeeCatalogs>{const supabase=getSupabaseClient();const[branches,departments,positions]=await Promise.all([supabase.from('branches').select('id,name').eq('status','active').order('name'),supabase.from('departments').select('id,name,branch_id').eq('is_active',true).order('name'),supabase.from('positions').select('id,name,department_id').eq('is_active',true).order('name')]);if(branches.error)throw branches.error;if(departments.error)throw departments.error;if(positions.error)throw positions.error;return{branches:branches.data??[],departments:departments.data??[],positions:positions.data??[]}},
  save:(input:EmployeeInput)=>invoke<{employee:EmployeeRecord}>({action:'save',employee:input}),
  toggle:(id:string,active:boolean)=>invoke<{id:string;active:boolean}>({action:'toggle',id,active}),
};
