import type{AuthChangeEvent,Session as SupabaseSession}from'@supabase/supabase-js';
import{navigationItems}from'../../app/navigation';
import{getSupabaseClient}from'../../infrastructure/supabase/client';
import type{Session}from'../../types';
type ProfileRow={id:string;status:string;full_name:string;role_id:string;roles:{name?:string;code?:string}|{name?:string;code?:string}[]|null};
const permissionCodes=[...new Set(['portal.acceder',...navigationItems.map(i=>i.permission)])];
const roleOf=(value:ProfileRow['roles'])=>Array.isArray(value)?value[0]:value;
export async function hydrateSession(authSession:SupabaseSession):Promise<Session>{const supabase=getSupabaseClient();const{data,error}=await supabase.from('profiles').select('id,status,full_name,role_id,roles(name,code)').eq('id',authSession.user.id).single();if(error||!data)throw new Error('Tu cuenta no tiene un perfil empresarial configurado.');const profile=data as unknown as ProfileRow;if(profile.status!=='active'){await supabase.auth.signOut();throw new Error('Tu acceso está inactivo. Contacta a un administrador.')}const checks=await Promise.all(permissionCodes.map(async codigo=>{const{data:allowed,error:rpcError}=await supabase.rpc('tiene_permiso',{codigo_permiso:codigo});if(rpcError)throw rpcError;return[codigo,allowed===true]as const}));const permissions=checks.filter(([,ok])=>ok).map(([codigo])=>codigo);if(!permissions.includes('portal.acceder')){await supabase.auth.signOut();throw new Error('Tu cuenta no tiene permiso para acceder al portal.')}const role=roleOf(profile.roles);return{id:authSession.user.id,email:authSession.user.email??'',name:profile.full_name,role:role?.name??'Usuario',roleCode:role?.code??'',status:profile.status,permissions}}
export const authService={async current(){const{data,error}=await getSupabaseClient().auth.getSession();if(error)throw error;return data.session?hydrateSession(data.session):null},async login(email:string,password:string){const{data,error}=await getSupabaseClient().auth.signInWithPassword({email,password});if(error)throw error;if(!data.session)throw new Error('Supabase no devolvió una sesión válida.');return hydrateSession(data.session)},async logout(){const{error}=await getSupabaseClient().auth.signOut();if(error)throw error},async requestPasswordReset(email:string){const{error}=await getSupabaseClient().auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/actualizar-password`});if(error)throw error},async updatePassword(password:string){const{error}=await getSupabaseClient().auth.updateUser({password});if(error)throw error},listen(callback:(event:AuthChangeEvent,session:SupabaseSession|null)=>void){return getSupabaseClient().auth.onAuthStateChange(callback).data.subscription}};
