package com.example.controlhorario.ui.employees

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import com.example.controlhorario.database.AttendanceEntity
import com.example.controlhorario.database.CompanySettingsEntity
import com.example.controlhorario.database.LaborCalendarDayEntity
import com.example.controlhorario.database.PayrollHistoryEntity
import com.example.controlhorario.database.PayrollSettingsEntity
import com.example.controlhorario.engine.PayrollCalculationEngine
import com.example.controlhorario.engine.PayrollPdfEngine
import com.example.controlhorario.engine.PayrollValidationEngine
import com.example.controlhorario.model.Employee
import com.example.controlhorario.model.PayrollResult
import com.example.controlhorario.ui.components.OSINETButton
import com.example.controlhorario.ui.components.OSINETTextField
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

@Composable
fun EmployeePayrollPreviewScreen(
    employee: Employee?,
    attendanceRecords: List<AttendanceEntity>,
    laborCalendarDays: List<LaborCalendarDayEntity>,
    generalSettings: PayrollSettingsEntity?,
    companySettings: CompanySettingsEntity?,
    employeePayrollSettingsViewModel: EmployeePayrollSettingsViewModel,
    payrollHistoryViewModel: PayrollHistoryViewModel,
    onBack: () -> Unit
) {
    val context = LocalContext.current

    if (employee == null) {
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(24.dp)
        ) {
            Text("Empleado no encontrado")

            Spacer(modifier = Modifier.height(16.dp))

            OutlinedButton(
                onClick = onBack,
                modifier = Modifier.fillMaxWidth()
            ) {
                Text("⬅ Volver")
            }
        }
        return
    }

    LaunchedEffect(employee.id) {
        employeePayrollSettingsViewModel.loadSettings(employee.id)
    }

    val employeeSettings by employeePayrollSettingsViewModel.settings.collectAsState()

    val today = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).format(Date())

    var periodStart by remember { mutableStateOf(today) }
    var periodEnd by remember { mutableStateOf(today) }
    var message by remember { mutableStateOf("") }
    var payrollResult by remember { mutableStateOf<PayrollResult?>(null) }
    var payrollGenerated by remember { mutableStateOf(false) }
    var pdfPath by remember { mutableStateOf("") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(24.dp)
            .verticalScroll(rememberScrollState())
    ) {
        Text(
            text = "Vista previa de nómina",
            style = MaterialTheme.typography.headlineMedium
        )

        Spacer(modifier = Modifier.height(6.dp))

        Text(
            text = employee.nombre,
            style = MaterialTheme.typography.titleMedium
        )

        Spacer(modifier = Modifier.height(20.dp))

        OSINETTextField(
            value = periodStart,
            onValueChange = {
                periodStart = it
                payrollGenerated = false
                pdfPath = ""
            },
            label = "Fecha inicio yyyy-MM-dd",
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(10.dp))

        OSINETTextField(
            value = periodEnd,
            onValueChange = {
                periodEnd = it
                payrollGenerated = false
                pdfPath = ""
            },
            label = "Fecha final yyyy-MM-dd",
            modifier = Modifier.fillMaxWidth()
        )

        Spacer(modifier = Modifier.height(16.dp))

        OSINETButton(
            text = "🧮 Calcular vista previa",
            onClick = {
                val validation = PayrollValidationEngine.validateEmployeePayroll(
                    employee = employee,
                    periodStart = periodStart,
                    periodEnd = periodEnd,
                    attendanceRecords = attendanceRecords,
                    generalSettings = generalSettings,
                    employeeSettings = employeeSettings
                )

                if (!validation.isValid) {
                    payrollResult = null
                    payrollGenerated = false
                    pdfPath = ""
                    message = validation.message
                    return@OSINETButton
                }

                payrollResult = PayrollCalculationEngine.calculateEmployeePayroll(
                    employee = employee,
                    periodStart = periodStart,
                    periodEnd = periodEnd,
                    attendanceRecords = attendanceRecords,
                    laborCalendarDays = laborCalendarDays,
                    workScheduleTemplate = null,
                    generalSettings = generalSettings,
                    employeeSettings = employeeSettings
                )

                payrollGenerated = false
                pdfPath = ""
                message = "Vista previa calculada correctamente ✅"
            }
        )

        Spacer(modifier = Modifier.height(16.dp))

        if (message.isNotBlank()) {
            Text(message)
            Spacer(modifier = Modifier.height(12.dp))
        }

        if (pdfPath.isNotBlank()) {
            Text("PDF guardado en:")
            Text(pdfPath)
            Spacer(modifier = Modifier.height(12.dp))
        }

        payrollResult?.let { result ->
            PayrollResultCard(result = result)

            Spacer(modifier = Modifier.height(16.dp))

            OSINETButton(
                text = "✅ Generar nómina",
                onClick = {
                    if (payrollGenerated) {
                        message = "Esta nómina ya fue generada en esta vista previa."
                        return@OSINETButton
                    }

                    val createdAt = SimpleDateFormat(
                        "yyyy-MM-dd HH:mm:ss",
                        Locale.getDefault()
                    ).format(Date())

                    val history = PayrollHistoryEntity(
                        employeeId = result.employeeId,
                        employeeName = result.employeeName,
                        periodStart = result.periodStart,
                        periodEnd = result.periodEnd,
                        totalIncome = result.totalIncome,
                        totalDiscounts = result.totalDiscounts,
                        netPay = result.netPay,
                        oneTimeCreditAmount = result.oneTimeCreditAmount,
                        createdAt = createdAt
                    )

                    payrollHistoryViewModel.saveHistory(history)

                    if (result.temporaryCreditMustBeCleared) {
                        employeePayrollSettingsViewModel.clearOneTimeCredit()
                    }

                    payrollGenerated = true
                    message = "Nómina generada correctamente ✅"
                }
            )

            Spacer(modifier = Modifier.height(12.dp))

            OSINETButton(
                text = "📄 Generar recibo PDF",
                onClick = {
                    val pdfResult = PayrollPdfEngine.generatePayrollReceiptPdf(
                        context = context,
                        company = companySettings,
                        employee = employee,
                        result = result
                    )

                    if (pdfResult.success) {
                        pdfPath = pdfResult.displayPath
                        message = "Recibo PDF generado correctamente ✅"
                    } else {
                        pdfPath = ""
                        message = "Error al generar PDF: ${pdfResult.errorMessage}"
                    }
                }
            )
        }

        Spacer(modifier = Modifier.height(20.dp))

        OutlinedButton(
            onClick = onBack,
            modifier = Modifier.fillMaxWidth()
        ) {
            Text("⬅ Volver")
        }
    }
}

@Composable
private fun PayrollResultCard(
    result: PayrollResult
) {
    val currency = NumberFormat.getCurrencyInstance(Locale("es", "DO"))

    Card(
        modifier = Modifier.fillMaxWidth(),
        shape = RoundedCornerShape(18.dp),
        colors = CardDefaults.cardColors(
            containerColor = Color(0xFF111111)
        ),
        elevation = CardDefaults.cardElevation(defaultElevation = 6.dp)
    ) {
        Column(modifier = Modifier.padding(18.dp)) {
            Text("📅 Período: ${result.periodStart} - ${result.periodEnd}", color = Color.White)

            Spacer(modifier = Modifier.height(14.dp))

            Text("HORAS", color = Color.White, style = MaterialTheme.typography.titleMedium)
            Text("Normales: ${result.normalHours}", color = Color.White)
            Text("Extras: ${result.overtimeHours}", color = Color.White)
            Text("Nocturnas: ${result.nightHours}", color = Color.White)
            Text("Domingos: ${result.sundayHours}", color = Color.White)
            Text("Feriados: ${result.holidayHours}", color = Color.White)
            Text("Total trabajadas: ${result.totalWorkedHours}", color = Color.White)

            Spacer(modifier = Modifier.height(14.dp))

            Text("INGRESOS", color = Color.White, style = MaterialTheme.typography.titleMedium)
            Text("Sueldo base: ${currency.format(result.baseSalary)}", color = Color.White)
            Text("Horas normales: ${currency.format(result.normalHourPayment)}", color = Color.White)
            Text("Horas extras: ${currency.format(result.overtimePayment)}", color = Color.White)
            Text("Horas nocturnas: ${currency.format(result.nightPayment)}", color = Color.White)
            Text("Domingos: ${currency.format(result.sundayPayment)}", color = Color.White)
            Text("Feriados: ${currency.format(result.holidayPayment)}", color = Color.White)
            Text("Bonos: ${currency.format(result.bonusAmount)}", color = Color.White)
            Text("Comisiones: ${currency.format(result.commissionAmount)}", color = Color.White)
            Text("Otros ingresos: ${currency.format(result.otherIncomeAmount)}", color = Color.White)

            Spacer(modifier = Modifier.height(10.dp))

            Text("TOTAL DEVENGADO: ${currency.format(result.totalIncome)}", color = Color.White)

            Spacer(modifier = Modifier.height(14.dp))

            Text("DESCUENTOS", color = Color.White, style = MaterialTheme.typography.titleMedium)
            Text("AFP: ${currency.format(result.afpAmount)}", color = Color.White)
            Text("SFS: ${currency.format(result.sfsAmount)}", color = Color.White)
            Text("ISR: ${currency.format(result.isrAmount)}", color = Color.White)
            Text("Préstamo: ${currency.format(result.loanAmount)}", color = Color.White)
            Text("Cooperativa: ${currency.format(result.cooperativeAmount)}", color = Color.White)
            Text("Seguro privado: ${currency.format(result.privateInsuranceAmount)}", color = Color.White)
            Text("Celular: ${currency.format(result.phoneDiscountAmount)}", color = Color.White)
            Text("Comedor: ${currency.format(result.foodDiscountAmount)}", color = Color.White)
            Text("Transporte: ${currency.format(result.transportDiscountAmount)}", color = Color.White)
            Text("Crédito temporal: ${currency.format(result.oneTimeCreditAmount)}", color = Color.White)
            Text("Otros descuentos: ${currency.format(result.otherDiscountAmount)}", color = Color.White)

            Spacer(modifier = Modifier.height(10.dp))

            Text("TOTAL DESCUENTOS: ${currency.format(result.totalDiscounts)}", color = Color.White)

            Spacer(modifier = Modifier.height(16.dp))

            Text(
                text = "NETO A PAGAR: ${currency.format(result.netPay)}",
                color = Color(0xFF4CAF50),
                style = MaterialTheme.typography.titleLarge
            )

            if (result.temporaryCreditMustBeCleared) {
                Spacer(modifier = Modifier.height(12.dp))
                Text(
                    text = "⚠️ El crédito temporal se limpiará cuando se confirme la nómina.",
                    color = Color(0xFFFFC107)
                )
            }
        }
    }
}