$ErrorActionPreference='Stop'
function Has($path,$pattern,$label){if(-not(Select-String -LiteralPath $path -Pattern $pattern -Quiet)){throw "FALLO: $label"};Write-Host "OK: $label"}
Has 'contracts/attendance-rc2-v1.json' '"contractVersion": 1' 'contrato versionado'
Has 'contracts/attendance-rc2-v1.json' '"from":"FINALIZADA"' 'FINALIZADA irreversible en fixtures'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'unique\(empresa_id,empleado_id,fecha_laboral\)' 'una jornada por empleado y fecha'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'unique\(empresa_id,idempotency_key\)' 'idempotencia remota'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'enable row level security' 'RLS habilitada'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'jornadas\.ver_asignadas' 'alcance supervisor'
Has 'supabase/migrations/0002_FINAL.sql' 'create or replace function public\.obtener_empresa_actual\(\)' 'helper de empresa definido antes de 0008'
Has 'supabase/migrations/0002_FINAL.sql' 'create or replace function public\.obtener_empleado_actual_id\(\)' 'helper de empleado definido antes de 0008'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'e\.empresa_id=public\.obtener_empresa_actual\(\)' 'supervisor aislado por empresa autenticada'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'e\.supervisor_id=public\.obtener_empleado_actual_id\(\)' 'supervisor resuelto desde perfil autenticado'
if(Select-String -LiteralPath 'supabase/migrations/0008_rc2_attendance_engine.sql' -Pattern 'public\.(current_company_id|current_employee_id)\(' -Quiet){throw 'FALLO: 0008 referencia helpers inexistentes'}
Write-Host 'OK: 0008 usa exclusivamente helpers existentes'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'cerrar_jornadas_incompletas' 'cierre diario idempotente'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'cerrar_jornadas_vencidas' 'cierre por zona empresarial'
Has 'supabase/migrations/0008_rc2_attendance_engine.sql' 'v_minutos<15' 'tolerancia 15 minutos inclusiva'
Has 'supabase/functions/attendance-sync/index.ts' 'DEVICE_REVOKED' 'revocacion de dispositivo'
Has 'supabase/functions/attendance-sync/index.ts' 'registrar_evento_jornada_dispositivo' 'RPC atomica'
Has 'app/src/main/java/database/DatabaseProvider.kt' 'Migration\(28,29\)' 'migracion Room 28 a 29'
Has 'app/src/main/java/database/JourneyDao.kt' '@Transaction' 'transaccion jornada evento outbox'
Has 'app/src/main/java/database/JourneyDao.kt' 'insertLegacy' 'compatibilidad nomina'
Has 'app/src/main/java/attendance/AttendanceSyncWorker.kt' 'CONFLICTO' 'conflicto local'
Has 'app/src/main/java/attendance/AttendanceSyncWorker.kt' 'status in 400\.\.499' 'revocacion sin reintento infinito'
Has 'app/src/main/java/ui/punch/Rc2EmployeeAttendanceScreen.kt' 'JourneyStateEngine.allowedActions' 'botones desde motor canonico'
Has 'web/src/App.tsx' "from'./pages/JourneyPages'" 'rutas web reales'
Has 'web/src/App.tsx' 'Rc2DashboardPage as DashboardPage' 'dashboard real'
Has 'web/src/pages/JourneyPages.tsx' 'jornadas.admin_off_on' 'ADMIN-OFF ON protegido'
if(Select-String -LiteralPath 'web/src/pages/JourneyPages.tsx' -Pattern 'mockData' -Quiet){throw 'FALLO: jornadas web usa mocks'}
Write-Host 'Fundacion integral RC2 verificada.'
