$ErrorActionPreference='Stop'
function Has($path,$pattern,$label){if(-not(Select-String -LiteralPath $path -Pattern $pattern -Quiet)){throw "FALLO: $label"};Write-Host "OK: $label"}
$edge='supabase/functions/employee-sync/index.ts'
$model='app/src/main/java/model/Employee.kt'
$migration='app/src/main/java/database/DatabaseProvider.kt'
$scheduler='app/src/main/java/com/example/controlhorario/device/DeviceSyncScheduler.kt'
$repository='app/src/main/java/com/example/controlhorario/device/EmployeeSyncRepository.kt'
Has $edge "eq\('empresa_id',auth\.empresa_id\)" 'aislamiento por empresa'
Has $edge "eq\('estado','activo'\)" 'dispositivo activo'
Has $edge "eq\('token_hash',await hash\(credential\)\)" 'credencial hasheada validada'
Has $edge 'filter\(row=>row\.activo===true\)' 'payload completo solo de activos'
Has $edge 'inactive=page\.filter' 'tombstones de inactivos'
Has $edge 'cursorUpdatedAt.*cursorId' 'cursor incremental estable'
if(Select-String -LiteralPath $edge -Pattern 'pin_hash|template|biometr' -Quiet){throw 'FALLO: employee-sync expone PIN o biometria'}
Has $model 'remoteSupervisorId' 'supervisor remoto en Room'
Has $model 'remoteDepartmentId' 'departamento remoto en Room'
Has $model 'payType' 'tipo de pago en Room'
Has $repository 'findByRemoteId' 'merge por remote_id'
Has $repository 'mergeInactive' 'bajas remotas conservando datos locales'
Has $migration 'Migration\(27,28\)' 'migracion Room 27 a 28'
Has $scheduler 'NetworkType\.CONNECTED' 'espera regreso de Internet'
Has $scheduler 'enqueueUniqueWork' 'sincronizacion inmediata unica'
Has $scheduler 'PeriodicWorkRequestBuilder<EmployeeSyncWorker>\(6,TimeUnit\.HOURS\)' 'sincronizacion periodica'
Write-Host 'Modulo 2.2 de sincronizacion verificado.'
