$ErrorActionPreference='Stop'
function Has($path,$pattern,$label){if(-not(Select-String -LiteralPath $path -Pattern $pattern -Quiet)){throw "FALLO: $label"};Write-Host "OK: $label"}
$sql='supabase/migrations/0009_rc3_supervisor_scoped_operations.sql'
Has $sql 'supervisor_puede_ver_empleado' 'alcance canonico'
Has $sql "r\.code='supervisor'" 'rol supervisor activo'
Has $sql 'perfil_sucursales ps' 'sucursales autorizadas'
Has $sql 'perfil_departamentos pd' 'departamentos autorizados'
Has $sql 'SUPERVISOR_DEPARTMENT_BRANCH_NOT_AUTHORIZED' 'integridad sucursal departamento'
Has $sql 'SUPERVISOR_BRANCH_HAS_ASSIGNED_DEPARTMENTS' 'no elimina sucursal con departamentos asignados'
Has $sql 'not public\.es_supervisor_actual\(\)' 'expediente completo bloqueado'
Has $sql 'listar_empleados_supervisor' 'ficha operativa segura'
Has $sql 'dashboard_supervisor' 'dashboard real por alcance'
Has $sql 'corregir_jornada_supervisor' 'correccion transaccional'
Has $sql 'registrar_jornada_manual_supervisor' 'registro manual autorizado'
Has $sql 'SECUENCIA_TEMPORAL_INVALIDA' 'secuencia temporal validada'
Has $sql 'MOTIVO_REQUERIDO' 'motivo obligatorio'
Has $sql 'supervisor_auditoria' 'auditoria antes despues'
Has $sql 'notificaciones_internas' 'notificaciones internas'
Has $sql 'establecer_jornada_habilitada' 'ADMIN-OFF ON seguro'
Has $sql 'horarios_empleados' 'horarios versionados'
Has $sql 'update public\.empleados set updated_at=now\(\)' 'cambio de horario avanza cursor employee-sync'
Has 'web/src/pages/SupervisorPages.tsx' 'Dashboard de mi equipo' 'dashboard supervisor web'
Has 'web/src/pages/SupervisorPages.tsx' 'no expone expediente' 'empleado operativo sin expediente'
Has 'web/src/pages/SupervisorPages.tsx' 'new-event' 'incidencia nueva estilo neon'
Has 'web/src/pages/SupervisorPages.tsx' 'setSeverity' 'filtro de severidad en jornadas'
Has 'web/src/pages/SupervisorPages.tsx' 'setEmployment' 'filtro de estado laboral'
Has 'web/src/pages/SupervisorPages.tsx' 'markIncidentRead' 'marcar incidencia leida'
if(Select-String -LiteralPath 'web/src/pages/SupervisorPages.tsx' -Pattern 'mockData|pin_hash' -Quiet){throw 'FALLO: UI supervisor usa mock o dato sensible'}
Write-Host 'OK: UI supervisor sin mocks ni sensibles'
Has 'supabase/functions/employee-sync/index.ts' 'horarios_empleados' 'horario sincronizado'
Has 'app/src/main/java/model/Employee.kt' 'remoteScheduleStart' 'horario operativo Room'
Has 'app/src/main/java/database/DatabaseProvider.kt' 'Migration\(29,30\)' 'migracion Room 29 a 30'
Has 'app/src/main/java/ui/punch/EmployeePunchViewModel.kt' 'jornadaEnabled' 'ADMIN-OFF bloquea antes de huella'
Write-Host 'RC3 Supervisor verificado contractualmente.'
