import { useEffect, useMemo, useState } from 'react';
import { Eye, Plus, Search } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge, Empty, PageHeader, Toast } from '../components/UI';
import { employeeService, type EmployeeRecord, type EmployeeStatus } from '../modules/employees/employeeService';

export function EmployeesPage() {
  const [items, setItems] = useState<EmployeeRecord[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState<EmployeeStatus | 'todos'>('todos'); const [branch, setBranch] = useState(''); const [department, setDepartment] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); setError(''); try { setItems(await employeeService.list()); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible cargar empleados.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const rows = useMemo(() => items.filter((employee) => (status === 'todos' || employee.status === status) && (!branch || employee.branchName === branch) && (!department || employee.departmentName === department) && `${employee.code} ${employee.name} ${employee.cedula}`.toLowerCase().includes(query.trim().toLowerCase())), [items, query, status, branch, department]);
  const toggle = async (employee: EmployeeRecord) => { if (!window.confirm(`${employee.active ? 'ADMIN-OFF' : 'ADMIN-ON'} para ${employee.name}?`)) return; try { await employeeService.toggle(employee.id, !employee.active); await load(); setMessage(employee.active ? 'Empleado desactivado mediante baja lógica.' : 'Empleado activado.'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'No fue posible cambiar el estado.'); } };
  return <><PageHeader eyebrow="CAPITAL HUMANO" title="Empleados" description="Expedientes laborales con alcance protegido por permisos y RLS." action={<div className="button-row"><button className="secondary">Exportar PDF</button><button className="secondary">Exportar Excel</button><button className="secondary" onClick={() => window.print()}>Imprimir</button><Link className="primary" to="/empleados/nuevo"><Plus />Nuevo empleado</Link></div>} />{error && <div className="error">{error}</div>}<div className="toolbar"><div className="search"><Search /><input placeholder="Buscar por código, nombre o cédula" value={query} onChange={(event) => setQuery(event.target.value)} /></div><div className="filter-row"><select value={branch} onChange={(event) => setBranch(event.target.value)}><option value="">Todas las sucursales</option>{[...new Set(items.map((item) => item.branchName).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="">Todos los departamentos</option>{[...new Set(items.map((item) => item.departmentName).filter(Boolean))].map((value) => <option key={value}>{value}</option>)}</select><select value={status} onChange={(event) => setStatus(event.target.value as EmployeeStatus | 'todos')}><option value="todos">Todos los estados</option><option value="activo">Activos</option><option value="licencia">Licencia</option><option value="suspendido">Suspendidos</option><option value="desvinculado">Desvinculados</option></select><Badge tone="gray">{rows.length} registros</Badge></div></div><section className="table-wrap payroll-wide"><table><thead><tr><th>Código</th><th>Nombre</th><th>Cédula</th><th>Empresa</th><th>Sucursal</th><th>Departamento</th><th>Cargo</th><th>Supervisor</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map((employee) => <tr key={employee.id}><td>{employee.code}</td><td>{employee.name}</td><td>{employee.cedula || 'No registrada'}</td><td>Empresa autorizada</td><td>{employee.branchName || 'Sin asignar'}</td><td>{employee.departmentName || 'Sin asignar'}</td><td>{employee.positionName || 'Sin asignar'}</td><td>No disponible</td><td><button className="chip" onClick={() => void toggle(employee)}><Badge tone={employee.active ? 'green' : 'gray'}>{employee.status}</Badge></button></td><td><div className="button-row"><Link className="icon" to={`/empleados/${employee.id}`} aria-label="Ver"><Eye /></Link><Link className="secondary" to={`/empleados/${employee.id}/editar`}>Editar</Link></div></td></tr>)}</tbody></table>{loading ? <Empty text="Cargando empleados…" /> : !rows.length && <Empty text="No hay empleados que coincidan con los filtros." />}</section><Toast message={message} /></>;
}
