import{FormEvent,useEffect,useRef,useState}from'react';
import{Banknote,BriefcaseBusiness,RefreshCw,Send,UserRound}from'lucide-react';
import{employeePortalService,type EmployeePortal}from'../modules/employeePortal/employeePortalService';
const money=(v:number)=>new Intl.NumberFormat('es-DO',{style:'currency',currency:'DOP'}).format(v||0);const date=(v?:string)=>v?new Date(`${v.slice(0,10)}T12:00:00`).toLocaleDateString('es-DO'):'—';
export function EmployeePortalPage(){
 const[data,setData]=useState<EmployeePortal|null>(null),[section,setSection]=useState('perfil'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[message,setMessage]=useState(''),[amount,setAmount]=useState(''),[discount,setDiscount]=useState(''),[reason,setReason]=useState(''),[busy,setBusy]=useState(false);const key=useRef(crypto.randomUUID());
 async function load(){setLoading(true);setError('');try{setData(await employeePortalService.get())}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar tu portal.')}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent){e.preventDefault();const total=Number(amount),quota=Number(discount);if(total<=0||quota<=0||quota>total||reason.trim().length<3){setError('Revisa el monto, la cuota y el motivo.');return}setBusy(true);setError('');try{await employeePortalService.requestLoan(total,quota,reason.trim(),key.current);key.current=crypto.randomUUID();setAmount('');setDiscount('');setReason('');setMessage('Solicitud enviada para revisión.');await load()}catch(x){setError(x instanceof Error?x.message:'No fue posible enviar la solicitud.')}finally{setBusy(false)}}
 async function cancel(id:string){if(!window.confirm('¿Cancelar esta solicitud?'))return;setBusy(true);setError('');try{await employeePortalService.cancelRequest(id);setMessage('Solicitud cancelada.');await load()}catch(e){setError(e instanceof Error?e.message:'No fue posible cancelar.')}finally{setBusy(false)}}
 return <><header className="employee-hero"><span>ACCESO PRIVADO</span><h1>Mi portal</h1><p>Información personal, ganancias y préstamos asociados exclusivamente a tu cuenta.</p><button className="secondary" onClick={()=>void load()} disabled={loading}><RefreshCw/>Actualizar</button></header>{error&&<div className="error">{error}</div>}{message&&<div className="success">{message}</div>}
 <nav className="employee-sections" aria-label="Secciones del portal">{[['perfil','PERFIL',UserRound],['ganancias','GANANCIAS HOY',Banknote],['prestamo','PRÉSTAMO',BriefcaseBusiness],['solicitud','SOLICITUD DE PRÉSTAMO',Send]].map(([id,label,Icon])=><button key={String(id)} className={section===id?'active':''} onClick={()=>setSection(String(id))}><Icon/><b>{String(label)}</b></button>)}</nav>
 {loading?<div className="empty">Cargando información segura…</div>:data&&<section className="panel employee-content">
 {section==='perfil'&&<div className="employee-profile"><h2>{data.perfil.nombre}</h2><dl><dt>Código</dt><dd>{data.perfil.codigo}</dd><dt>Correo</dt><dd>{data.perfil.correo||'—'}</dd><dt>Teléfono</dt><dd>{data.perfil.telefono||'—'}</dd><dt>Sucursal</dt><dd>{data.perfil.sucursal||'—'}</dd><dt>Departamento</dt><dd>{data.perfil.departamento||'—'}</dd><dt>Puesto</dt><dd>{data.perfil.puesto||'—'}</dd><dt>Estado</dt><dd>{data.perfil.estado}</dd><dt>Ingreso</dt><dd>{date(data.perfil.fecha_ingreso)}</dd></dl></div>}
 {section==='ganancias'&&<div><h2>Acumulado hasta ayer</h2><p>{date(data.ganancias.periodo_inicio)} — {date(data.ganancias.periodo_fin)} · corte {date(data.ganancias.corte)}</p><div className="stats employee-stats"><article className="stat"><span>Pago normal</span><strong>{money(data.ganancias.pago_normal)}</strong><small>{Math.round(data.ganancias.minutos_normales/60*100)/100} h</small></article><article className="stat"><span>Horas extra</span><strong>{money(data.ganancias.pago_extra)}</strong><small>{Math.round(data.ganancias.minutos_extra/60*100)/100} h</small></article><article className="stat"><span>Incentivo</span><strong>{money(data.ganancias.incentivo)}</strong></article><article className="stat"><span>Total acumulado</span><strong>{money(data.ganancias.total)}</strong><small>No incluye el día de hoy</small></article></div></div>}
 {section==='prestamo'&&<div><h2>Mis préstamos</h2>{!data.prestamos.length?<div className="empty">No tienes préstamos registrados.</div>:data.prestamos.map(loan=><article className="employee-loan" key={loan.id}><header><b>{money(loan.monto_total)}</b><span>{loan.estado}</span></header><p>Total pagado: <strong>{money(loan.pagado)}</strong> · Pendiente: <strong>{money(loan.pendiente)}</strong> · Cuota actual: {money(loan.descuento_periodo)} · Cuotas restantes: {Math.ceil(loan.pendiente/Math.max(loan.descuento_periodo,1))}</p><small>{loan.motivo}</small><h3>Historial aplicado</h3>{!loan.movimientos.length?<p>No hay descuentos aplicados.</p>:<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Movimiento</th><th>Monto</th><th>Antes</th><th>Después</th><th>Referencia</th></tr></thead><tbody>{loan.movimientos.map(m=><tr key={m.id}><td>{new Date(m.creado_en).toLocaleDateString('es-DO')}</td><td>{m.tipo}</td><td>{money(m.monto)}</td><td>{money(m.saldo_anterior)}</td><td>{money(m.saldo_posterior)}</td><td>{m.referencia||'—'}</td></tr>)}</tbody></table></div>}</article>)}</div>}
 {section==='solicitud'&&<div className="employee-request"><form className="form-grid" onSubmit={submit}><h2>Solicitar préstamo</h2><label>Monto solicitado<input type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Descuento por período<input type="number" min="0.01" step="0.01" value={discount} onChange={e=>setDiscount(e.target.value)} required/></label><label className="wide">Motivo<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={3} maxLength={1000} required/></label><button className="primary" disabled={busy}>{busy?'Enviando…':'Enviar solicitud'}</button></form><h2>Mis solicitudes</h2>{!data.solicitudes.length?<div className="empty">No has enviado solicitudes.</div>:data.solicitudes.map(x=><article className="employee-loan" key={x.id}><header><b>{money(x.monto_solicitado)}</b><span>{x.estado}</span></header><p>Cuota propuesta: {money(x.descuento_periodo)}</p><small>{x.motivo} · {new Date(x.creada_en).toLocaleString('es-DO')}</small>{['PENDIENTE_REVISION','EN_REVISION'].includes(x.estado)&&<button className="secondary danger" disabled={busy} onClick={()=>void cancel(x.id)}>Cancelar solicitud</button>}</article>)}</div>}
 </section>}</>;
}
