import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {PageHeader,Empty} from '../components/UI';
import {payrollService,type AdjustmentRow,type PayrollEmployee,type PayrollSnapshot} from '../modules/payroll/payrollService';

type Draft={loan:number;credit:number;other:number};
type RowStatus={kind:'Guardando…'|'Guardado'|'Error';message?:string};
const money=(value:number)=>`RD$ ${value.toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function PayrollDiscountsPage(){
 const [employees,setEmployees]=useState<PayrollEmployee[]>([]),[snapshot,setSnapshot]=useState<PayrollSnapshot|null>(null),[period,setPeriod]=useState(''),[drafts,setDrafts]=useState<Record<string,Draft>>({}),[status,setStatus]=useState<Record<string,RowStatus>>({}),[error,setError]=useState('');
 useEffect(()=>{void(async()=>{try{const periods=await payrollService.listPeriods();const active=periods[0]?.id??'';setPeriod(active);const [people,data]=await Promise.all([payrollService.listEmployees(),active?payrollService.get(active):Promise.resolve(null)]);setEmployees(people.sort((a,b)=>a.codigo.localeCompare(b.codigo)));setSnapshot(data)}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar descuentos.') }})()},[]);
 const credits=useMemo(()=>new Map((snapshot?.creditos??[]).filter(c=>c.estado==='ACTIVO').map(c=>[c.empleado_id,c.monto_total])),[snapshot]);
 const get=(id:string)=>drafts[id]??{loan:0,credit:0,other:0};
 const update=(id:string,key:keyof Draft,value:string)=>{const amount=Math.max(0,Number(value)||0);setDrafts(all=>({...all,[id]:{...get(id),[key]:amount}}));};
 async function apply(employee:PayrollEmployee){const row=get(employee.id);const rows:AdjustmentRow[]=[];([['loan','DESCU-PRES'],['credit','DESCU-CRED'],['other','OTRO_DESCUENTO']]as const).forEach(([key,tipo])=>{if(row[key]>0)rows.push({codigo:employee.codigo,tipo,monto:row[key]})});setStatus(all=>({...all,[employee.id]:{kind:'Guardando…'}}));try{if(period&&rows.length)await payrollService.applyAdjustments(period,rows,'MANUAL','Descuentos por empleado');setStatus(all=>({...all,[employee.id]:{kind:'Guardado'}}));}catch(e){setStatus(all=>({...all,[employee.id]:{kind:'Error',message:e instanceof Error?e.message:'Error al guardar'}}));}}
 return <><PageHeader eyebrow="NOMINA" title="Descuentos" description="Aplica descuentos unicamente al empleado seleccionado." action={<Link className="secondary" to="/nomina">Volver a nomina</Link>}/>{error&&<div className="error">{error}</div>}{!employees.length?<Empty text="No hay empleados activos disponibles."/>:<section className="table-wrap payroll-wide"><table><thead><tr><th>Codigo</th><th>Nombre</th><th>Desc. Prestamo</th><th>Credito Total</th><th>Desc. Credito</th><th>Otros Descuentos</th><th>Aplicar</th></tr></thead><tbody>{employees.map(employee=>{const row=get(employee.id);const state=status[employee.id];return <tr key={employee.id}><td>{employee.codigo}</td><td>{employee.nombre}</td><td><input type="number" min="0" step="0.01" value={row.loan} onChange={e=>update(employee.id,'loan',e.target.value)}/></td><td>{money(credits.get(employee.id)??0)}</td><td><input type="number" min="0" step="0.01" value={row.credit} onChange={e=>update(employee.id,'credit',e.target.value)}/></td><td><input type="number" min="0" step="0.01" value={row.other} onChange={e=>update(employee.id,'other',e.target.value)}/></td><td><button className="primary" disabled={state?.kind==='Guardando…'} onClick={()=>void apply(employee)}>Aplicar</button><small>{state?.kind}{state?.message?`: ${state.message}`:''}</small></td></tr>})}</tbody></table></section>}</>;
}
