import { useCallback,useEffect,useState,type FormEvent } from 'react';
import { Calculator,Download,FileDown,FileSpreadsheet,RefreshCw,Upload } from 'lucide-react';
import { Link,useSearchParams } from 'react-router-dom';
import { Badge,Empty,PageHeader,Toast } from '../components/UI';
import { useAuth } from '../context/AuthContext';
import { downloadFinalExcel,downloadPayrollPdf,downloadPayrollTemplate,parsePayrollTemplate,type ImportPreview } from '../modules/payroll/payrollExports';
import { PayrollApiError,payrollService,type AdjustmentRow,type PayrollEmployee,type PayrollPeriod,type PayrollSnapshot,type PayrollState } from '../modules/payroll/payrollService';

const today=()=>new Date().toISOString().slice(0,10);const money=(value:number|undefined)=>`RD$ ${Number(value??0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function errorText(error:unknown){if(error instanceof PayrollApiError)return [error.code,error.message,error.details,error.hint].filter(Boolean).join(' · ');return error instanceof Error?error.message:'Error desconocido';}
const tone=(state:string)=>state==='CERRADA'||state==='APROBADA'?'green':state==='ANULADA'?'red':state==='EN_REVISION'?'amber':'blue';

export function PayrollPage(){
 const{session,hasPermission}=useAuth();const[searchParams,setSearchParams]=useSearchParams();const view=searchParams.get('vista')??'procesamiento';const viewTab=view==='prestamos'?'prestamos':view==='creditos'?'creditos':view==='historial'?'auditoria':'detalle';const[periods,setPeriods]=useState<PayrollPeriod[]>([]),[employees,setEmployees]=useState<PayrollEmployee[]>([]),[selected,setSelected]=useState(''),[snapshot,setSnapshot]=useState<PayrollSnapshot|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[tab,setTab]=useState<'detalle'|'descuentos'|'prestamos'|'creditos'|'auditoria'>(viewTab);const[preview,setPreview]=useState<ImportPreview|null>(null),[importFile,setImportFile]=useState<File|null>(null);
 const[periodForm,setPeriodForm]=useState({from:today(),to:today(),type:'QUINCENAL' as 'QUINCENAL'|'MENSUAL'});const[adjustment,setAdjustment]=useState({employee:'',type:'ROTUR/FALT' as AdjustmentRow['tipo'],amount:'',reason:''});const[finance,setFinance]=useState({employee:'',total:'',perPeriod:'',date:today(),reason:''});
 const load=useCallback(async(preferred?:string)=>{setLoading(true);setError('');try{const[p,e]=await Promise.all([payrollService.listPeriods(),payrollService.listEmployees()]);setPeriods(p);setEmployees(e);const id=preferred??selected??p[0]?.id??'';setSelected(id);setSnapshot(id?await payrollService.get(id):null)}catch(e){setError(errorText(e));setSnapshot(null)}finally{setLoading(false)}},[selected]);
 useEffect(()=>{void load()},[]);// eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{setTab(viewTab)},[viewTab]);
 function selectTab(next:typeof tab){setTab(next);const route=next==='prestamos'?'prestamos':next==='creditos'?'creditos':next==='auditoria'?'historial':next==='detalle'?'procesamiento':next;setSearchParams(route==='procesamiento'?{}:{vista:route},{replace:true})}
 async function choose(id:string){setSelected(id);setLoading(true);setError('');try{setSnapshot(await payrollService.get(id))}catch(e){setError(errorText(e));setSnapshot(null)}finally{setLoading(false)}}
 async function run(action:()=>Promise<unknown>,success:string){setBusy(true);setError('');try{await action();setMessage(success);await load(selected);return true}catch(e){setError(errorText(e));return false}finally{setBusy(false)}}
 async function createPeriod(event:FormEvent){event.preventDefault();let id='';setBusy(true);setError('');try{id=await payrollService.createPeriod(periodForm.from,periodForm.to,periodForm.type);setMessage('Período creado');await load(id)}catch(e){setError(errorText(e))}finally{setBusy(false)}}
 async function transition(state:PayrollState){const reason=window.prompt(`Motivo para cambiar a ${state}:`)?.trim();if(!reason)return;await run(()=>payrollService.changeState(selected,state,reason),`Nómina ${state.toLowerCase()}`)}
 async function addAdjustment(event:FormEvent){event.preventDefault();const employee=employees.find(e=>e.id===adjustment.employee);if(!employee)return setError('Selecciona un empleado.');await run(()=>payrollService.applyAdjustments(selected,[{codigo:employee.codigo,tipo:adjustment.type,monto:Number(adjustment.amount)}],'MANUAL',adjustment.reason),'Ajuste guardado');setAdjustment(v=>({...v,amount:'',reason:''}))}
 async function createFinance(kind:'loan'|'credit',event:FormEvent){event.preventDefault();const fn=kind==='loan'?payrollService.createLoan:payrollService.createCredit;await run(()=>fn(finance.employee,Number(finance.total),Number(finance.perPeriod),finance.date,finance.reason),kind==='loan'?'Préstamo creado como pendiente':'Crédito creado');setFinance(v=>({...v,total:'',perPeriod:'',reason:''}))}
 async function readImport(file:File){setImportFile(file);setPreview(await parsePayrollTemplate(file,employees))}
 async function applyImport(){if(!preview||preview.issues.length||!preview.rows.length)return;if(await run(async()=>{await payrollService.applyAdjustments(selected,preview.rows,'EXCEL',`Carga ${importFile?.name??'Excel'}`);await payrollService.registerExport(selected,'IMPORTACION',importFile?.name??'importacion.xlsx',{filas:preview.sourceRows,ajustes:preview.rows.length})},'Plantilla aplicada sin errores')){setPreview(null);setImportFile(null)}}
 async function exportFile(type:'template'|'excel'|'pdf'){if(!selected)return;try{if(type==='template'){await downloadPayrollTemplate(employees);await payrollService.registerExport(selected,'PLANTILLA','plantilla-descuentos-nomina.xlsx',{empleados:employees.length})}else if(snapshot&&type==='excel'){const name=`nomina-${snapshot.periodo.fecha_inicio}-${snapshot.periodo.fecha_fin}.xlsx`;await downloadFinalExcel(snapshot,name);await payrollService.registerExport(selected,'EXCEL_FINAL',name,{version:snapshot.nomina.version_calculo})}else if(snapshot){const name=`nomina-${snapshot.periodo.fecha_inicio}-${snapshot.periodo.fecha_fin}.pdf`;await downloadPayrollPdf(snapshot,`Empresa ${session?.companyId.slice(0,8)}`,name);await payrollService.registerExport(selected,'PDF_FINAL',name,{version:snapshot.nomina.version_calculo})}setMessage('Archivo generado y auditado')}catch(e){setError(errorText(e))}}
 const summary=snapshot?.nomina.resumen??{};
 return <>
  <PageHeader eyebrow="RC4 · MOTOR CENTRAL" title="Nómina" description="Períodos, jornadas consolidadas, descuentos, préstamos, créditos y exportaciones auditadas." action={<div className="button-row"><button className="secondary" onClick={()=>void load(selected)} disabled={loading||busy}><RefreshCw/>Actualizar</button>{hasPermission('nomina.generar')&&selected&&<button className="primary" onClick={()=>void run(()=>payrollService.calculate(selected),'Nómina calculada')} disabled={busy}><Calculator/>Calcular / recalcular</button>}</div>}/>
  {error&&<div className="error payroll-error"><b>No fue posible completar la operación.</b><span>{error}</span></div>}
  <section className="panel payroll-periods"><form className="payroll-create" onSubmit={createPeriod}><label>Desde<input type="date" value={periodForm.from} onChange={e=>setPeriodForm(v=>({...v,from:e.target.value}))} required/></label><label>Hasta<input type="date" value={periodForm.to} onChange={e=>setPeriodForm(v=>({...v,to:e.target.value}))} required/></label><label>Tipo<select value={periodForm.type} onChange={e=>setPeriodForm(v=>({...v,type:e.target.value as 'QUINCENAL'|'MENSUAL'}))}><option>QUINCENAL</option><option>MENSUAL</option></select></label><button className="primary" disabled={busy||!hasPermission('nomina.generar')}>Crear período</button></form><label>Período activo<select value={selected} onChange={e=>void choose(e.target.value)}><option value="">Selecciona un período</option>{periods.map(p=><option key={p.id} value={p.id}>{p.fecha_inicio} → {p.fecha_fin} · {p.estado}</option>)}</select></label></section>
  {loading?<Empty text="Cargando nómina real…"/>:!snapshot?<Empty text="Crea o selecciona un período para comenzar."/>:<>
   <section className="payroll-status panel"><div><span>Estado</span><Badge tone={tone(snapshot.periodo.estado) as 'blue'|'green'|'amber'|'red'}>{snapshot.periodo.estado}</Badge>{snapshot.nomina.desactualizada&&<Badge tone="red">Requiere recálculo</Badge>}</div><div className="button-row">{snapshot.periodo.estado==='CALCULADA'&&hasPermission('nomina.editar')&&<button className="secondary" onClick={()=>void transition('EN_REVISION')}>Enviar a revisión</button>}{snapshot.periodo.estado==='EN_REVISION'&&hasPermission('nomina.aprobar')&&<button className="secondary" onClick={()=>void transition('APROBADA')}>Aprobar</button>}{snapshot.periodo.estado==='APROBADA'&&hasPermission('nomina.cerrar')&&<button className="primary" onClick={()=>void transition('CERRADA')}>Cerrar nómina</button>}{!['CERRADA','ANULADA'].includes(snapshot.periodo.estado)&&hasPermission('nomina.anular')&&<button className="secondary danger" onClick={()=>void transition('ANULADA')}>Anular</button>}</div></section>
   <section className="stats payroll-stats">{[['Empleados',summary.empleados],['Total sueldos',money(summary.total_sueldos)],['Horas extras',money(summary.total_horas_extras)],['Incentivos',money(summary.total_incentivos)],['Préstamos',money(summary.total_prestamos)],['Impuestos',money(summary.total_impuestos)],['Otros descuentos',money(summary.total_otros_descuentos)],['TOTAL PAGADO',money(summary.total_general_pagado)]].map(([label,value])=><article className="stat" key={String(label)}><span>{label}</span><strong>{value??0}</strong><small>Versión {snapshot.nomina.version_calculo}</small></article>)}</section>
   <div className="payroll-tabs">{(['detalle','descuentos','prestamos','creditos','auditoria'] as const).map(t=><button className={tab===t?'chip active':'chip'} key={t} onClick={()=>selectTab(t)}>{t}</button>)}{hasPermission('prestamos.solicitudes_ver')&&<Link className="chip" to="/nomina/solicitudes">solicitudes</Link>}</div>
   {tab==='detalle'&&<><div className="button-row payroll-exports"><button className="secondary" onClick={()=>void exportFile('template')}><Download/>Descargar plantilla</button><button className="secondary" onClick={()=>void exportFile('excel')} disabled={!snapshot.detalles.length}><FileSpreadsheet/>Excel final</button><button className="secondary" onClick={()=>void exportFile('pdf')} disabled={!snapshot.detalles.length}><FileDown/>PDF final</button></div><section className="table-wrap"><table><thead><tr><th>Código</th><th>Empleado</th><th>Base</th><th>Horas</th><th>Extras</th><th>Nocturnas</th><th>Impuestos</th><th>Descuentos</th><th>Neto</th></tr></thead><tbody>{snapshot.detalles.map(d=><tr key={d.id}><td>{d.codigo_empleado}</td><td><b>{d.nombre_empleado}</b><small>{d.tipo_pago} · {d.formula}</small></td><td>{money(d.sueldo_base)}</td><td>{d.horas_normales}</td><td>{d.horas_extras} / {money(d.total_horas_extras)}</td><td>{d.horas_nocturnas} / {money(d.total_nocturnas)}</td><td>{money(d.total_impuestos)}</td><td>{money(d.total_descuentos)}</td><td><b>{money(d.neto)}</b></td></tr>)}</tbody></table>{!snapshot.detalles.length&&<Empty text="Este período todavía no ha sido calculado."/>}</section></>}
   {tab==='descuentos'&&<div className="payroll-grid"><form className="panel form-grid payroll-form" onSubmit={addAdjustment}><h2>Ajuste manual auditado</h2><label>Empleado<select value={adjustment.employee} onChange={e=>setAdjustment(v=>({...v,employee:e.target.value}))} required><option value="">Selecciona</option>{employees.map(e=><option value={e.id} key={e.id}>{e.codigo} · {e.nombre}</option>)}</select></label><label>Tipo<select value={adjustment.type} onChange={e=>setAdjustment(v=>({...v,type:e.target.value as AdjustmentRow['tipo']}))}>{['DESCU-PRES','DESCU-CRED','ROTUR/FALT','OTRO_DESCUENTO','INCENTIVO'].map(x=><option key={x}>{x}</option>)}</select></label><label>Monto<input type="number" min="0.01" step="0.01" value={adjustment.amount} onChange={e=>setAdjustment(v=>({...v,amount:e.target.value}))} required/></label><label>Motivo<input value={adjustment.reason} onChange={e=>setAdjustment(v=>({...v,reason:e.target.value}))} required/></label><button className="primary" disabled={busy||!hasPermission('nomina.descuentos')}>Guardar ajuste</button></form><section className="panel upload compact"><Upload/><h2>Plantilla Excel</h2><input type="file" accept=".xlsx,.xls" onChange={e=>{const file=e.target.files?.[0];if(file)void readImport(file)}}/>{preview&&<div className={preview.issues.length?'error':'success'}>{preview.issues.length?<><b>{preview.issues.length} errores; no se aplicó ninguna fila.</b>{preview.issues.slice(0,8).map((x,i)=><small key={i}>Fila {x.row} · {x.field}: {x.message}</small>)}</>:<><b>Vista previa válida</b><small>{preview.sourceRows} empleados · {preview.rows.length} descuentos con monto.</small></>}</div>}<button className="primary" disabled={!preview||!!preview.issues.length||!preview.rows.length||busy} onClick={()=>void applyImport()}>Aplicar plantilla</button></section></div>}
   {(tab==='prestamos'||tab==='creditos')&&<div className="payroll-grid"><form className="panel form-grid payroll-form" onSubmit={e=>void createFinance(tab==='prestamos'?'loan':'credit',e)}><h2>Nuevo {tab==='prestamos'?'préstamo':'crédito'}</h2><label>Empleado<select value={finance.employee} onChange={e=>setFinance(v=>({...v,employee:e.target.value}))} required><option value="">Selecciona</option>{employees.map(x=><option key={x.id} value={x.id}>{x.codigo} · {x.nombre}</option>)}</select></label><label>Total<input type="number" min="0.01" step="0.01" value={finance.total} onChange={e=>setFinance(v=>({...v,total:e.target.value}))} required/></label><label>Descuento por período<input type="number" min="0.01" step="0.01" value={finance.perPeriod} onChange={e=>setFinance(v=>({...v,perPeriod:e.target.value}))} required/></label><label>Fecha inicio<input type="date" value={finance.date} onChange={e=>setFinance(v=>({...v,date:e.target.value}))} required/></label><label>Motivo<input value={finance.reason} onChange={e=>setFinance(v=>({...v,reason:e.target.value}))} required/></label><button className="primary" disabled={busy}>Crear</button></form><section className="table-wrap"><table><thead><tr><th>Empleado</th><th>Total</th><th>Pagado</th><th>Pendiente</th><th>Por período</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{(tab==='prestamos'?snapshot.prestamos:snapshot.creditos).map(item=>{const e=employees.find(x=>x.id===item.empleado_id);const paid='total_pagado'in item?item.total_pagado:item.total_descontado;return <tr key={item.id}><td>{e?.nombre??item.empleado_id}</td><td>{money(item.monto_total)}</td><td>{money(paid)}</td><td>{money(item.pendiente)}</td><td>{money(item.descuento_periodo)}</td><td><Badge tone={tone(item.estado) as 'blue'|'green'|'amber'|'red'}>{item.estado}</Badge></td><td className="button-row">{tab==='prestamos'&&item.estado==='PENDIENTE'&&<button className="secondary" onClick={()=>void run(()=>payrollService.changeLoanState(item.id,'APROBADO','Aprobación administrativa'),'Préstamo aprobado')}>Aprobar</button>}{tab==='prestamos'&&item.estado==='APROBADO'&&<button className="secondary" onClick={()=>void run(()=>payrollService.changeLoanState(item.id,'ENTREGADO','Entrega confirmada'),'Préstamo entregado')}>Entregar</button>}{tab==='creditos'&&item.estado==='ACTIVO'&&<button className="secondary danger" onClick={()=>void run(()=>payrollService.cancelCredit(item.id,'Cancelación administrativa'),'Crédito cancelado')}>Cancelar</button>}</td></tr>})}</tbody></table></section></div>}
   {tab==='auditoria'&&<section className="table-wrap"><table><thead><tr><th>Fecha</th><th>Acción</th><th>Empleado</th><th>Motivo</th></tr></thead><tbody>{snapshot.auditoria.map(a=><tr key={a.id}><td>{new Date(a.fecha).toLocaleString()}</td><td><Badge>{a.accion}</Badge></td><td>{employees.find(e=>e.id===a.empleado_id)?.nombre??'—'}</td><td>{a.motivo??'—'}</td></tr>)}</tbody></table></section>}
  </>}
  <Toast message={message}/>
 </>;
}
