import { useEffect, useMemo, useState } from 'react';
import { Empty } from '../components/UI';
import { reportDataService, type Journey } from '../modules/reports/reportDataService';
import { ExpandableReportTable, emptyReportFilters, ReadOnlyReport, ReportStat } from '../modules/reports/ReadOnlyReport';
import type { ReportFiltersValue } from '../modules/reports/ReportFilters';
import type { PayrollLoan } from '../modules/payroll/payrollService';

const money = (value?: number) => value == null ? 'No disponible' : new Intl.NumberFormat('es-DO', { style: 'currency', currency: 'DOP' }).format(value);
const hours = (minutes: number) => `${Math.round((minutes / 60) * 100) / 100} h`;
const matchesJourney = (journey: Journey, filters: ReportFiltersValue) => (!filters.branch || journey.branch === filters.branch) && (!filters.department || journey.department === filters.department) && (!filters.employee || `${journey.code} ${journey.employee}`.toLowerCase().includes(filters.employee.toLowerCase())) && (!filters.from || journey.workDate >= filters.from) && (!filters.to || journey.workDate <= filters.to);
function useReportFilters() { return useState<ReportFiltersValue>(emptyReportFilters); }
function useLoad<T>(load: () => Promise<T>) { const [data, setData] = useState<T | null>(null); const [error, setError] = useState(''); useEffect(() => { load().then(setData).catch((reason) => setError(reason instanceof Error ? reason.message : 'No fue posible cargar el reporte.')); }, [load]); return { data, error }; }
function ErrorMessage({ error }: { error: string }) { return error ? <div className="error">{error}</div> : null; }

export function PayrollReportPage() {
  const [filters, setFilters] = useReportFilters(); const { data, error } = useLoad(reportDataService.payroll);
  const rows = useMemo(() => data?.snapshot?.detalles.filter((detail) => !filters.employee || `${detail.codigo_empleado} ${detail.nombre_empleado}`.toLowerCase().includes(filters.employee.toLowerCase())) ?? [], [data, filters.employee]);
  const summary = data?.snapshot?.nomina.resumen;
  return <ReadOnlyReport title="Reporte de Nómina" description="Resultados calculados del último período disponible." filters={filters} onFiltersChange={setFilters} summary={<><ReportStat label="Empleados" value={summary?.empleados ?? rows.length} /><ReportStat label="Sueldos" value={money(summary?.total_sueldos)} /><ReportStat label="Horas extras" value={money(summary?.total_horas_extras)} /><ReportStat label="Total neto" value={money(summary?.total_general_pagado)} /></>}><ErrorMessage error={error} /><ExpandableReportTable rows={rows} rowKey={(row) => row.id} empty="No hay detalles de nómina disponibles." columns={[{ label: 'Código', value: (row) => row.codigo_empleado }, { label: 'Empleado', value: (row) => row.nombre_empleado }, { label: 'Sueldo bruto', value: (row) => money(row.bruto) }, { label: 'Horas extras', value: (row) => hours(Math.round(row.horas_extras * 60)) }, { label: 'Pago extras', value: (row) => money(row.total_horas_extras) }, { label: 'Descuentos', value: (row) => money(row.total_descuentos) }, { label: 'Neto', value: (row) => money(row.neto) }]} detail={(row) => <p>Horas normales: {row.horas_normales} · AFP: {money(row.afp)} · SFS: {money(row.sfs)} · Préstamo: {money(row.descuento_prestamo)} · Crédito: {money(row.descuento_credito)} · Fórmula registrada: {row.formula || 'No disponible'}.</p>} /></ReadOnlyReport>;
}

export function LoansReportPage() {
  const [filters, setFilters] = useReportFilters(); const { data, error } = useLoad(reportDataService.payroll); const [status, setStatus] = useState('');
  const rows = useMemo(() => (data?.snapshot?.prestamos ?? []).filter((loan) => { const employee = data?.employees.find((item) => item.id === loan.empleado_id); return (!status || loan.estado === status) && (!filters.employee || `${employee?.codigo ?? ''} ${employee?.nombre ?? ''}`.toLowerCase().includes(filters.employee.toLowerCase())); }), [data, filters.employee, status]);
  const name = (loan: PayrollLoan) => data?.employees.find((employee) => employee.id === loan.empleado_id)?.nombre ?? loan.empleado_id;
  return <ReadOnlyReport title="Reporte de Préstamos" description="Saldos registrados para el período disponible." filters={filters} onFiltersChange={setFilters} extraFilters={<label>Estado<select value={status} onChange={(event) => setStatus(event.target.value)}><option value="">Todos</option>{['PENDIENTE', 'APROBADO', 'PAGADO', 'CANCELADO'].map((value) => <option key={value}>{value}</option>)}</select></label>} summary={<><ReportStat label="Préstamos" value={rows.length} /><ReportStat label="Monto original" value={money(rows.reduce((total, row) => total + row.monto_total, 0))} /><ReportStat label="Total pagado" value={money(rows.reduce((total, row) => total + row.total_pagado, 0))} /><ReportStat label="Pendiente" value={money(rows.reduce((total, row) => total + row.pendiente, 0))} /></>}><ErrorMessage error={error} /><ExpandableReportTable rows={rows} rowKey={(row) => row.id} empty="No hay préstamos para los filtros aplicados." columns={[{ label: 'Empleado', value: name }, { label: 'Fecha inicio', value: (row) => row.fecha_inicio }, { label: 'Monto', value: (row) => money(row.monto_total) }, { label: 'Pagado', value: (row) => money(row.total_pagado) }, { label: 'Pendiente', value: (row) => money(row.pendiente) }, { label: 'Estado', value: (row) => row.estado }]} detail={(row) => <p>Cuota registrada: {money(row.descuento_periodo)} · Fecha final: {row.fecha_final ?? 'No disponible'} · Observación: {row.motivo || 'Sin observación'}.</p>} /></ReadOnlyReport>;
}

export function ProductivityReportPage() {
  const [filters, setFilters] = useReportFilters(); const { data, error } = useLoad(reportDataService.journeys); const rows = (data ?? []).filter((journey) => matchesJourney(journey, filters)); const total = rows.reduce((sum, row) => sum + row.workedMinutes, 0);
  return <ReadOnlyReport title="Reporte de Productividad" description="Tiempo efectivo registrado por jornada." filters={filters} onFiltersChange={setFilters} summary={<><ReportStat label="Jornadas" value={rows.length} /><ReportStat label="Empleados" value={new Set(rows.map((row) => row.employeeId)).size} /><ReportStat label="Tiempo efectivo" value={hours(total)} /><ReportStat label="Promedio por jornada" value={rows.length ? hours(total / rows.length) : '0 h'} /></>}><ErrorMessage error={error} /><ExpandableReportTable rows={rows} rowKey={(row) => row.id} empty="No hay jornadas para los filtros aplicados." columns={[{ label: 'Fecha', value: (row) => row.workDate }, { label: 'Código', value: (row) => row.code }, { label: 'Empleado', value: (row) => row.employee }, { label: 'Sucursal', value: (row) => row.branch }, { label: 'Departamento', value: (row) => row.department }, { label: 'Tiempo trabajado', value: (row) => hours(row.workedMinutes) }, { label: 'Pausas', value: (row) => hours(row.breakMinutes) }, { label: 'Estado', value: (row) => row.status }]} detail={(row) => <p>Tiempo efectivo registrado: {hours(row.workedMinutes)} · Pausas registradas: {hours(row.breakMinutes)} · Incidencias: {row.incidents.map((item) => item.message).join(' · ') || 'Ninguna'}.</p>} /></ReadOnlyReport>;
}

export function IncidentsReportPage() {
  const [filters, setFilters] = useReportFilters(); const { data, error } = useLoad(reportDataService.incidents); const [openOnly, setOpenOnly] = useState(false); const rows = (data ?? []).filter((row) => matchesJourney(row.journey, filters) && (!openOnly || !row.resolved));
  return <ReadOnlyReport title="Reporte de Incidencias" description="Incidencias registradas en jornadas, sin acciones de edición." filters={filters} onFiltersChange={setFilters} extraFilters={<label><input type="checkbox" checked={openOnly} onChange={(event) => setOpenOnly(event.target.checked)} /> Solo pendientes</label>} summary={<><ReportStat label="Incidencias" value={rows.length} /><ReportStat label="Pendientes" value={rows.filter((row) => !row.resolved).length} /><ReportStat label="Alta o crítica" value={rows.filter((row) => ['ALTA', 'CRITICA'].includes(row.severity)).length} /><ReportStat label="Jornadas afectadas" value={new Set(rows.map((row) => row.journey.id)).size} /></>}><ErrorMessage error={error} /><ExpandableReportTable rows={rows} rowKey={(row) => row.id} empty="No hay incidencias para los filtros aplicados." columns={[{ label: 'Fecha', value: (row) => row.journey.workDate }, { label: 'Empleado', value: (row) => row.journey.employee }, { label: 'Sucursal', value: (row) => row.journey.branch }, { label: 'Tipo', value: (row) => row.type }, { label: 'Severidad', value: (row) => row.severity }, { label: 'Estado', value: (row) => row.resolved ? 'Resuelta' : 'Pendiente' }, { label: 'Mensaje', value: (row) => row.message }]} detail={(row) => <p>Creada: {row.createdAt} · Minutos asociados: {row.minutes ?? 'No disponible'} · Jornada: {row.journey.status} · Actualización registrada: {row.journey.updatedAt}.</p>} /></ReadOnlyReport>;
}

export function TerminatedEmployeesReportPage() {
  const [filters, setFilters] = useReportFilters(); const { data, error } = useLoad(reportDataService.inactiveEmployees); const rows = (data ?? []).filter((employee) => (!filters.branch || employee.branchName === filters.branch) && (!filters.department || employee.departmentName === filters.department) && (!filters.employee || `${employee.code} ${employee.name}`.toLowerCase().includes(filters.employee.toLowerCase())));
  return <ReadOnlyReport title="Reporte de Empleados Dados de Baja" description="Empleados inactivos visibles dentro del alcance autorizado." filters={filters} onFiltersChange={setFilters} summary={<><ReportStat label="Empleados dados de baja" value={rows.length} /><ReportStat label="Sucursales" value={new Set(rows.map((row) => row.branchName)).size} /><ReportStat label="Departamentos" value={new Set(rows.map((row) => row.departmentName)).size} /><ReportStat label="Con salario registrado" value={rows.filter((row) => row.salary != null).length} /></>}><ErrorMessage error={error} /><ExpandableReportTable rows={rows} rowKey={(row) => row.id} empty="No hay empleados dados de baja para los filtros aplicados." columns={[{ label: 'Código', value: (row) => row.code }, { label: 'Empleado', value: (row) => row.name }, { label: 'Sucursal', value: (row) => row.branchName }, { label: 'Departamento', value: (row) => row.departmentName }, { label: 'Estado', value: (row) => row.status }, { label: 'Ingreso', value: (row) => row.startDate || 'No disponible' }]} detail={(row) => <p>Cargo: {row.positionName || 'No disponible'} · Tipo de pago: {row.payType || 'No disponible'} · Salario registrado: {money(row.salary ?? undefined)}.</p>} /></ReadOnlyReport>;
}

export function HolidaysReportPage() {
  const [filters, setFilters] = useReportFilters(); const { data, error } = useLoad(reportDataService.journeys); const rows = (data ?? []).filter((journey) => matchesJourney(journey, filters) && journey.incidents.some((incident) => /FESTIV/i.test(`${incident.type} ${incident.message}`)));
  return <ReadOnlyReport title="Reporte de Días Festivos Trabajados" description="Solo jornadas con una marca festiva registrada." filters={filters} onFiltersChange={setFilters} summary={<><ReportStat label="Jornadas festivas" value={rows.length} /><ReportStat label="Empleados" value={new Set(rows.map((row) => row.employeeId)).size} /><ReportStat label="Horas trabajadas" value={hours(rows.reduce((sum, row) => sum + row.workedMinutes, 0))} /><ReportStat label="Pago adicional" value="No disponible" /></>}><ErrorMessage error={error} /><ExpandableReportTable rows={rows} rowKey={(row) => row.id} empty="No hay jornadas con marca festiva registrada." columns={[{ label: 'Fecha', value: (row) => row.workDate }, { label: 'Código', value: (row) => row.code }, { label: 'Empleado', value: (row) => row.employee }, { label: 'Sucursal', value: (row) => row.branch }, { label: 'Horas trabajadas', value: (row) => hours(row.workedMinutes) }, { label: 'Estado', value: (row) => row.status }]} detail={(row) => <p>Marca festiva registrada: {row.incidents.filter((item) => /FESTIV/i.test(`${item.type} ${item.message}`)).map((item) => item.message).join(' · ')}. El importe adicional no se infiere si no está registrado.</p>} /></ReadOnlyReport>;
}

export function PermissionsReportPage() {
  const [filters, setFilters] = useReportFilters(); const { data, error } = useLoad(reportDataService.permissionsAndLicenses); const rows = (data ?? []).filter((employee) => (!filters.branch || employee.branchName === filters.branch) && (!filters.department || employee.departmentName === filters.department) && (!filters.employee || `${employee.code} ${employee.name}`.toLowerCase().includes(filters.employee.toLowerCase())));
  return <ReadOnlyReport title="Reporte de Permisos y Licencias" description="Licencias registradas y visibles dentro del alcance autorizado." filters={filters} onFiltersChange={setFilters} summary={<><ReportStat label="Licencias registradas" value={rows.length} /><ReportStat label="Empleados" value={new Set(rows.map((row) => row.id)).size} /><ReportStat label="Sucursales" value={new Set(rows.map((row) => row.branchName)).size} /><ReportStat label="Estado" value="Solo lectura" /></>}><ErrorMessage error={error} /><ExpandableReportTable rows={rows} rowKey={(row) => row.id} empty="No hay permisos o licencias disponibles para los filtros aplicados." columns={[{ label: 'Código', value: (row) => row.code }, { label: 'Empleado', value: (row) => row.name }, { label: 'Sucursal', value: (row) => row.branchName }, { label: 'Departamento', value: (row) => row.departmentName }, { label: 'Estado', value: (row) => row.status }, { label: 'Fecha ingreso', value: (row) => row.startDate || 'No disponible' }]} detail={(row) => <p>Las fechas, tipo y observaciones del permiso no se muestran porque no están disponibles en el servicio actual. Cargo: {row.positionName || 'No disponible'}.</p>} /></ReadOnlyReport>;
}
