import{useEffect as reactUseEffect,useMemo,useState,type ReactNode}from'react';
import{AlertTriangle,Clock3,Coffee,ShieldCheck,TimerReset,Users}from'lucide-react';
import{Badge,Empty,PageHeader}from'../components/UI';
import{useAuth}from'../context/AuthContext';
import{supervisorService,type SupervisorAudit,type SupervisorDashboard,type SupervisorEmployee,type SupervisorIncident,type SupervisorJourney,type SupervisorSchedule}from'../modules/supervisor/supervisorService';
import{dashboardErrorMessage,logDashboardFailure}from'../modules/dashboard/dashboardDiagnostics';
const err=(e:unknown)=>dashboardErrorMessage(e);
const ask=(label:string)=>prompt(label)?.trim()||'';
const localInput=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):'';
const useEffect=(callback:()=>unknown,deps:unknown[])=>reactUseEffect(()=>{void callback()},deps);
function Load({loading,error,children}:{loading:boolean;error:string;children:ReactNode}){if(error)return <div className="error">{error}</div>;return loading?<Empty text="Cargando datos protegidos…"/>:<>{children}</>}
export function SupervisorDashboardPage(){
 const{session}=useAuth(),[data,setData]=useState<SupervisorDashboard|null>(null),[error,setError]=useState('');
 useEffect(()=>{supervisorService.dashboard().then(setData).catch(e=>{logDashboardFailure('rpc dashboard_supervisor',e,session);setError(err(e))})},[session]);
 const stats=data?[["Equipo",data.total_empleados,Users],["Activos",data.activos,Users],["Sin iniciar",data.sin_iniciar,Clock3],["En curso",data.en_curso,ShieldCheck],["En pausa",data.en_pausa,Coffee],["Finalizadas",data.finalizadas,TimerReset],["Pendientes",data.pendientes,AlertTriangle],["Incidencias",data.incidencias_nuevas,AlertTriangle],["ADMIN-OFF",data.jornadas_deshabilitadas,AlertTriangle]]as const:[];
 return <><PageHeader eyebrow="SUPERVISOR RC3" title="Dashboard de mi equipo" description="Alcance real por sucursal y departamento."/><Load loading={!data&&!error} error={error}>
  <section className="stats">{stats.map(([label,count,Icon])=><article className="stat" key={label}><div className="stat-icon blue"><Icon/></div><span>{label}</span><strong>{count}</strong><small>{data?.fecha_laboral}</small></article>)}</section>
  <div className="dashboard-grid"><section className="panel"><h2>Actividad reciente</h2>{data?.recientes.length?data.recientes.map(x=><article className="employee-cell" key={x.id}><b>{x.codigo} · {x.nombre}</b><p>{x.estado} · {x.severidad}</p></article>):<Empty text="Sin actividad del equipo."/>}</section><section className="panel"><h2>Incidencias y empleados sin iniciar</h2>{data?.incidencias.length?data.incidencias.map(x=><article className="new-event panel" key={`${x.tipo}-${x.id}`}><b>{x.nombre} · {x.tipo}</b><p>{x.mensaje}</p></article>):<Empty text="Sin incidencias ni empleados pendientes de iniciar."/>}</section></div>
 </Load></>
}
export function SupervisorEmployeesPage(){
 const{hasPermission}=useAuth(),[items,setItems]=useState<SupervisorEmployee[]>([]),[query,setQuery]=useState(''),[branch,setBranch]=useState(''),[department,setDepartment]=useState(''),[employment,setEmployment]=useState(''),[enabled,setEnabled]=useState(''),[error,setError]=useState('');
 const load=()=>supervisorService.employees().then(setItems).catch(e=>setError(err(e)));useEffect(load,[]);
 const filtered=useMemo(()=>items.filter(x=>(!query||`${x.codigo} ${x.nombre}`.toLowerCase().includes(query.toLowerCase()))&&(!branch||x.sucursal===branch)&&(!department||x.departamento===department)&&(!employment||x.estado_laboral===employment)&&(!enabled||String(x.jornada_habilitada)===enabled)),[items,query,branch,department,employment,enabled]);
 async function toggle(x:SupervisorEmployee){const reason=ask(`Motivo obligatorio para ADMIN-${x.jornada_habilitada?'OFF':'ON'}`);if(!reason)return;try{await supervisorService.setAttendance(x.id,!x.jornada_habilitada,reason);load()}catch(e){setError(err(e))}}
 async function manual(x:SupervisorEmployee){const date=ask('Fecha laboral YYYY-MM-DD'),reason=ask('Motivo obligatorio del registro manual');if(!date||!reason)return;try{await supervisorService.manual(x.id,date,{start:ask('Llegada ISO'),breakStart:ask('Inicio almuerzo ISO')||null,breakEnd:ask('Regreso almuerzo ISO')||null,end:ask('Salida ISO')},reason);load()}catch(e){setError(err(e))}}
 async function schedule(x:SupervisorEmployee){const reason=ask('Motivo obligatorio del horario'),date=ask('Vigente desde YYYY-MM-DD');if(!reason||!date)return;try{await supervisorService.saveSchedule({employeeId:x.id,date,start:ask('Entrada HH:MM'),end:ask('Salida HH:MM'),lunch:ask('Inicio almuerzo HH:MM')||null,duration:Number(ask('Duración almuerzo minutos')||60),days:[1,2,3,4,5],tolerance:Number(ask('Tolerancia minutos')||15),reason});load()}catch(e){setError(err(e))}}
 return <><PageHeader eyebrow="ALCANCE OPERATIVO" title="Empleados asignados" description="Ficha mínima; no expone expediente, salario, PIN ni biometría."/><div className="report-filters"><label>Buscar<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código o nombre"/></label><label>Sucursal<select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Todas</option>{[...new Set(items.map(x=>x.sucursal))].map(x=><option key={x}>{x}</option>)}</select></label><label>Departamento<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Todos</option>{[...new Set(items.map(x=>x.departamento))].map(x=><option key={x}>{x}</option>)}</select></label><label>Estado<select value={employment} onChange={e=>setEmployment(e.target.value)}><option value="">Todos</option>{[...new Set(items.map(x=>x.estado_laboral))].map(x=><option key={x}>{x}</option>)}</select></label><label>Jornada<select value={enabled} onChange={e=>setEnabled(e.target.value)}><option value="">Todas</option><option value="true">Habilitada</option><option value="false">Deshabilitada</option></select></label></div><Load loading={!items.length&&!error} error={error}><section className="table-wrap"><table><thead><tr><th>Empleado</th><th>Alcance</th><th>Cargo</th><th>Jornada</th><th>Estado</th><th>Horario</th><th/></tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td><b>{x.codigo} · {x.nombre}</b><small>{x.telefono||'Teléfono restringido'}</small></td><td>{x.sucursal} · {x.departamento}</td><td>{x.cargo}</td><td><Badge tone={x.jornada_habilitada?'green':'red'}>{x.jornada_habilitada?'ON':'OFF'}</Badge></td><td>{x.estado_laboral} · {x.estado_jornada}</td><td>{x.horario_resumen||'Sin horario'}</td><td><div className="button-row">{hasPermission('jornadas.admin_off_on')&&<button onClick={()=>toggle(x)}>ADMIN-{x.jornada_habilitada?'OFF':'ON'}</button>}{hasPermission('jornadas.corregir_asignadas')&&<button onClick={()=>manual(x)}>Tiempo manual</button>}{hasPermission('horarios.editar_asignados')&&<button onClick={()=>schedule(x)}>Horario</button>}</div></td></tr>)}</tbody></table></section></Load></>
}
const correctionValues=(j:SupervisorJourney)=>({start:ask('Llegada ISO (fecha y hora)')||localInput(j.iniciado_en),breakStart:ask('Inicio almuerzo ISO (vacío si no aplica)')||null,breakEnd:ask('Regreso almuerzo ISO (vacío si no aplica)')||null,end:ask('Salida ISO (fecha y hora)')||localInput(j.finalizado_en)});
export function SupervisorJourneysPage({pendingOnly=false}:{pendingOnly?:boolean}){
 const{hasPermission}=useAuth(),[items,setItems]=useState<SupervisorJourney[]>([]),[date,setDate]=useState(''),[status,setStatus]=useState(''),[severity,setSeverity]=useState(''),[branch,setBranch]=useState(''),[department,setDepartment]=useState(''),[query,setQuery]=useState(''),[error,setError]=useState('');
 const load=()=>supervisorService.journeys(date).then(setItems).catch(e=>setError(err(e)));useEffect(load,[date]);
 const rows=items.filter(x=>(!pendingOnly||x.revision_pendiente)&&(!status||x.estado===status)&&(!severity||x.severidad===severity)&&(!branch||x.sucursal===branch)&&(!department||x.departamento===department)&&(!query||`${x.codigo} ${x.nombre}`.toLowerCase().includes(query.toLowerCase())));
 async function decide(j:SupervisorJourney,decision:string){const reason=ask(`Motivo obligatorio: ${decision}`);if(!reason)return;try{await supervisorService.decide(j.id,decision,reason);load()}catch(e){setError(err(e))}}
 async function correct(j:SupervisorJourney){const reason=ask('Motivo obligatorio de corrección');if(!reason)return;try{await supervisorService.correct(j.id,correctionValues(j),reason);load()}catch(e){setError(err(e))}}
 return <><PageHeader eyebrow="JORNADAS ASIGNADAS" title={pendingOnly?'Pendientes del equipo':'Jornadas del equipo'} description="Detalle operativo, conflictos y acciones auditadas."/><div className="report-filters"><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Empleado<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código o nombre"/></label><label>Sucursal<select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Todas</option>{[...new Set(items.map(x=>x.sucursal))].map(x=><option key={x}>{x}</option>)}</select></label><label>Departamento<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="">Todos</option>{[...new Set(items.map(x=>x.departamento))].map(x=><option key={x}>{x}</option>)}</select></label><label>Estado<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{['SIN_INICIAR','EN_CURSO','EN_PAUSA','FINALIZADA'].map(x=><option key={x}>{x}</option>)}</select></label><label>Severidad<select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">Todas</option>{['NINGUNA','INFORMATIVA','MEDIA','ALTA','CRITICA'].map(x=><option key={x}>{x}</option>)}</select></label></div><Load loading={!items.length&&!error} error={error}><section className="table-wrap"><table><thead><tr><th>Empleado</th><th>Fecha</th><th>Estado</th><th>Tiempos</th><th>Pendiente</th><th>Acciones</th></tr></thead><tbody>{rows.map(j=><tr className={j.incidencias.some((incident:any)=>!incident.leida)?'new-event':''} key={j.id}><td><b>{j.codigo} · {j.nombre}</b><small>{j.sucursal} · {j.departamento}</small></td><td>{j.fecha_laboral}</td><td>{j.estado}</td><td>{j.minutos_trabajados} min · pausa {j.minutos_pausa}</td><td>{j.revision_pendiente?<Badge tone="red">{j.severidad}</Badge>:'No'}</td><td><div className="button-row">{hasPermission('jornadas.corregir_asignadas')&&<button onClick={()=>correct(j)}>Corregir</button>}{j.revision_pendiente&&hasPermission('jornadas.aprobar_pendientes_asignadas')&&<><button onClick={()=>decide(j,'APROBADA')}>Aprobar</button><button onClick={()=>decide(j,'RECHAZADA')}>Rechazar</button><button onClick={()=>decide(j,'DEVUELTA')}>Devolver</button></>}</div></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No hay jornadas en este alcance."/>}</section></Load></>
}
export function SupervisorIncidentsPage(){
 const{hasPermission}=useAuth(),[items,setItems]=useState<SupervisorIncident[]>([]),[error,setError]=useState('');
 const load=()=>supervisorService.incidents().then(setItems).catch(e=>setError(err(e)));useEffect(load,[]);
 async function markRead(x:SupervisorIncident){try{await supervisorService.markIncidentRead(x.id);load()}catch(e){setError(err(e))}}
 async function resolve(x:SupervisorIncident){const comment=ask('Comentario interno obligatorio');if(!comment)return;try{await supervisorService.resolveIncident(x.id,true,comment);load()}catch(e){setError(err(e))}}
 return <><PageHeader eyebrow="INCIDENCIAS RC3" title="Incidencias asignadas" description="Solo empleados dentro del alcance autorizado."/><Load loading={!items.length&&!error} error={error}><section className="table-wrap"><table><thead><tr><th>Empleado</th><th>Tipo</th><th>Severidad</th><th>Mensaje</th><th>Estado</th><th/></tr></thead><tbody>{items.map(x=><tr className={!x.leida?'new-event':''} key={x.id}><td>{x.codigo} · {x.nombre}<small>{x.sucursal} · {x.departamento}</small></td><td>{x.tipo}</td><td>{x.severidad}</td><td>{x.mensaje}{x.minutos!=null?` · ${x.minutos} min`:''}</td><td>{x.resuelta?'Resuelta':x.leida?'Leída':'Nueva'}</td><td><div className="button-row">{!x.leida&&<button onClick={()=>markRead(x)}>Marcar leída</button>}{!x.resuelta&&hasPermission('incidencias.resolver_asignadas')&&<button onClick={()=>resolve(x)}>Resolver</button>}</div></td></tr>)}</tbody></table></section></Load></>
}
export function SupervisorSchedulesPage(){const{hasPermission}=useAuth(),[items,setItems]=useState<SupervisorSchedule[]>([]),[error,setError]=useState('');const load=()=>supervisorService.schedules().then(setItems).catch(e=>setError(err(e)));useEffect(load,[]);async function edit(x:SupervisorSchedule){const reason=ask('Motivo obligatorio del cambio');if(!reason)return;try{await supervisorService.saveSchedule({employeeId:x.empleado_id,date:ask('Vigente desde YYYY-MM-DD')||x.fecha_vigencia,start:ask('Entrada HH:MM')||x.hora_entrada,end:ask('Salida HH:MM')||x.hora_salida,lunch:ask('Inicio almuerzo HH:MM')||x.inicio_almuerzo,duration:Number(ask('Duración almuerzo minutos')||x.duracion_almuerzo_min),days:x.dias_laborales,tolerance:Number(ask('Tolerancia minutos')||x.tolerancia_min),reason});load()}catch(e){setError(err(e))}}return <><PageHeader eyebrow="HORARIOS ASIGNADOS" title="Horarios del equipo" description="Cambios futuros, validados y auditados."/><Load loading={!items.length&&!error} error={error}><section className="table-wrap"><table><thead><tr><th>Empleado</th><th>Alcance</th><th>Vigencia</th><th>Horario</th><th>Almuerzo</th><th>Tolerancia</th><th/></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{x.codigo} · {x.nombre}</td><td>{x.sucursal} · {x.departamento}</td><td>{x.fecha_vigencia}</td><td>{x.hora_entrada} - {x.hora_salida}</td><td>{x.inicio_almuerzo||'—'} · {x.duracion_almuerzo_min} min</td><td>{x.tolerancia_min} min</td><td>{hasPermission('horarios.editar_asignados')&&<button onClick={()=>edit(x)}>Editar</button>}</td></tr>)}</tbody></table></section></Load></>}
export function SupervisorAuditPage(){const[items,setItems]=useState<SupervisorAudit[]>([]),[error,setError]=useState('');useEffect(()=>{supervisorService.audit().then(setItems).catch(e=>setError(err(e)))},[]);return <><PageHeader eyebrow="AUDITORÍA RC3" title="Historial operativo" description="Actor, fecha, antes, después y motivo de cada operación."/><Load loading={!items.length&&!error} error={error}><section className="table-wrap"><table><thead><tr><th>Fecha</th><th>Actor</th><th>Entidad</th><th>Acción</th><th>Motivo</th></tr></thead><tbody>{items.map(x=><tr key={x.id}><td>{new Date(x.fecha).toLocaleString()}</td><td>{x.actor_rol}</td><td>{x.entidad}</td><td>{x.accion}</td><td>{x.motivo}</td></tr>)}</tbody></table></section></Load></>}
