import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Badge, Empty, PageHeader } from '../components/UI';
import { administrationService, type OrganizationData, type Profile } from '../modules/administration/administrationService';

const empty: OrganizationData = { branches: [], departments: [], positions: [], profiles: [], employees: [], roles: [], permissions: [], departmentAssignments: [], rolePermissions: [] };
const reason = 'Actualización de asignaciones de supervisor';
function Exports() { return <div className="button-row"><button className="secondary">Exportar PDF</button><button className="secondary">Exportar Excel</button><button className="secondary" onClick={() => window.print()}>Imprimir</button></div>; }
function assignedDepartments(profile: Profile, data: OrganizationData) { return data.departments.filter((department) => data.departmentAssignments.some((assignment) => assignment.perfil_id === profile.id && assignment.departamento_id === department.id)); }

export function SupervisorsManagementPage({ detail = false }: { detail?: boolean }) {
  const { id } = useParams(); const [data, setData] = useState(empty); const [query, setQuery] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = () => administrationService.organization().then(setData).catch((failure) => setError(failure instanceof Error ? failure.message : 'No fue posible cargar supervisores.'));
  useEffect(() => { void load(); }, []);
  const supervisors = useMemo(() => data.profiles.filter((profile) => data.roles.find((role) => role.id === profile.role_id)?.code === 'supervisor').filter((profile) => `${profile.full_name} ${profile.phone ?? ''}`.toLowerCase().includes(query.toLowerCase())), [data, query]);
  const supervisor = data.profiles.find((profile) => profile.id === id && data.roles.find((role) => role.id === profile.role_id)?.code === 'supervisor');
  const changeStatus = async (profile: Profile) => { setBusy(true); try { await administrationService.updateUserStatus(profile.id, profile.status === 'active' ? 'inactive' : 'active', reason); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : 'No fue posible actualizar el supervisor.'); } finally { setBusy(false); } };
  const assign = async (departmentId: string, selected: boolean) => { if (!supervisor) return; const department = data.departments.find((item) => item.id === departmentId); if (!department) return; setBusy(true); try { await administrationService.saveDepartment(department.id, { code: department.code, name: department.name, branch_id: department.branch_id, description: department.description, is_active: department.is_active }, selected ? supervisor.id : null, reason); await load(); } catch (failure) { setError(failure instanceof Error ? failure.message : 'No fue posible asignar el departamento.'); } finally { setBusy(false); } };
  if (detail && !supervisor) return <Empty text="Supervisor no encontrado o fuera del alcance autorizado." />;
  if (detail && supervisor) { const departments = assignedDepartments(supervisor, data); const branches = [...new Set(departments.map((department) => data.branches.find((branch) => branch.id === department.branch_id)?.name ?? 'Corporativo'))]; const employees = data.employees.filter((employee) => departments.some((department) => employee.nombre_completo && department.id)); return <><PageHeader eyebrow="SUPERVISORES" title={supervisor.full_name} description="Administración limitada estrictamente a los departamentos asignados." action={<div className="button-row"><Link className="secondary" to="/supervisores">Volver</Link><button className="secondary" disabled={busy} onClick={() => void changeStatus(supervisor)}>{supervisor.status === 'active' ? 'Desactivar' : 'Activar'}</button></div>} />{error && <div className="error">{error}</div>}<section className="detail-grid panel"><div><small>Código</small><b>{supervisor.id.slice(0, 8)}</b></div><div><small>Correo</small><b>No disponible en perfil</b></div><div><small>Teléfono</small><b>{supervisor.phone ?? 'No disponible'}</b></div><div><small>Empresa</small><b>{supervisor.company_id}</b></div><div><small>Sucursales asignadas</small><b>{branches.join(', ') || 'Ninguna'}</b></div><div><small>Estado</small><b>{supervisor.status}</b></div></section><section className="dashboard-grid"><section className="panel"><h2>Departamentos asignados</h2>{data.departments.map((department) => { const selected = departments.some((item) => item.id === department.id); return <label className="employee-cell" key={department.id}><input type="checkbox" checked={selected} disabled={busy} onChange={(event) => void assign(department.id, event.target.checked)} />{department.name}<small>{data.branches.find((branch) => branch.id === department.branch_id)?.name ?? 'Corporativo'}</small></label>; })}</section><section className="panel"><h2>Empleados asignados</h2>{employees.length ? employees.map((employee) => <p key={employee.id}>{employee.codigo_empleado} · {employee.nombre_completo}</p>) : <Empty text="Los empleados visibles quedan limitados por los departamentos asignados y RLS." />}</section><section className="panel"><h2>Historial de cambios</h2><p>Las asignaciones y cambios de estado se registran mediante los servicios administrativos auditados.</p></section></section></>; }
  return <><PageHeader eyebrow="SUPERVISORES" title="Supervisores" description="Asignación explícita por departamento; nunca por sucursal completa." action={<Exports />} />{error && <div className="error">{error}</div>}<div className="toolbar"><input className="search" placeholder="Buscar por nombre o teléfono" value={query} onChange={(event) => setQuery(event.target.value)} /></div><section className="table-wrap payroll-wide"><table><thead><tr><th>Código</th><th>Nombre</th><th>Correo</th><th>Teléfono</th><th>Empresa</th><th>Sucursales</th><th>Departamentos</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{supervisors.map((profile) => { const departments = assignedDepartments(profile, data); const branches = [...new Set(departments.map((department) => data.branches.find((branch) => branch.id === department.branch_id)?.name ?? 'Corporativo'))]; return <tr key={profile.id}><td>{profile.id.slice(0, 8)}</td><td>{profile.full_name}</td><td>No disponible</td><td>{profile.phone ?? '—'}</td><td>{profile.company_id}</td><td>{branches.join(', ') || '—'}</td><td>{departments.map((department) => department.name).join(', ') || '—'}</td><td><Badge tone={profile.status === 'active' ? 'green' : 'gray'}>{profile.status}</Badge></td><td><div className="button-row"><Link className="secondary" to={`/supervisores/${profile.id}`}>Ver / Editar</Link><button className="secondary" disabled={busy} onClick={() => void changeStatus(profile)}>{profile.status === 'active' ? 'Desactivar' : 'Activar'}</button></div></td></tr>; })}</tbody></table>{!supervisors.length && <Empty text="No hay supervisores visibles en este alcance." />}</section></>;
}
