import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Badge, Empty, PageHeader } from '../components/UI';
import { authService } from '../modules/auth/authService';
import { administrationService, type AuditEvent, type OrganizationData, type Profile } from '../modules/administration/administrationService';

const empty: OrganizationData = { branches: [], departments: [], positions: [], profiles: [], employees: [], roles: [], permissions: [], departmentAssignments: [], rolePermissions: [] };
const roleLabels: Record<string, string> = { admin: 'Administrador', supervisor: 'Supervisor', rrhh: 'Recursos Humanos', nomina: 'Nómina', empleado: 'Empleado', consulta: 'Consulta' };
const roleLabel = (code?: string) => roleLabels[code ?? ''] ?? code ?? 'Sin rol';
function UserAudit({ profileId }: { profileId: string }) { const [items, setItems] = useState<AuditEvent[]>([]); useEffect(() => { administrationService.audit().then((events) => setItems(events.filter((event) => event.entidad_id === profileId))).catch(() => setItems([])); }, [profileId]); return <section className="panel"><h2>Historial de cambios y auditoría</h2>{items.length ? <div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Usuario</th><th>Acción</th><th>Motivo</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td>{item.fecha}</td><td>{item.actor_id ?? 'Sistema'}</td><td>{item.accion}</td><td>{item.motivo ?? 'Sin observación'}</td></tr>)}</tbody></table></div> : <Empty text="No hay eventos de auditoría disponibles para este usuario." />}</section>; }

function UserDetail({ profile, organization }: { profile: Profile; organization: OrganizationData }) { const role = organization.roles.find((item) => item.id === profile.role_id); const branch = organization.branches.find((item) => item.id === profile.branch_id); const department = organization.departments.find((item) => item.id === profile.department_id); const special = organization.rolePermissions.filter((item) => item.rol_id === profile.role_id && item.permitido).map((item) => organization.permissions.find((permission) => permission.id === item.permiso_id)?.codigo).filter(Boolean); return <><section className="detail-grid panel"><div><small>Código</small><b>{profile.id.slice(0, 8)}</b></div><div><small>Nombre</small><b>{profile.full_name}</b></div><div><small>Correo</small><b>No disponible en el perfil</b></div><div><small>Teléfono</small><b>{profile.phone ?? 'No disponible'}</b></div><div><small>Empresa</small><b>{profile.company_id}</b></div><div><small>Sucursal</small><b>{branch?.name ?? 'Sin asignar'}</b></div><div><small>Departamento</small><b>{department?.name ?? 'Sin asignar'}</b></div><div><small>Cargo</small><b>No disponible</b></div><div><small>Estado</small><b>{profile.status}</b></div><div><small>Fecha creación / último acceso</small><b>No disponible</b></div></section><section className="panel"><h2>Rol y permisos especiales</h2><p>Rol: <b>{roleLabel(role?.code)}</b>. Permisos efectivos del rol: {special.length ? special.join(', ') : 'Sin permisos adicionales registrados'}.</p></section><UserAudit profileId={profile.id} /></>; }

export function UsersAdministrationPage({ mode = 'list' }: { mode?: 'list' | 'view' | 'edit' | 'audit' }) { const { id } = useParams(); const [organization, setOrganization] = useState(empty); const [reason, setReason] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); useEffect(() => { administrationService.organization().then(setOrganization).catch((failure) => setError(failure instanceof Error ? failure.message : 'No fue posible cargar usuarios.')); }, []); const profile = organization.profiles.find((item) => item.id === id); const save = async (action: () => Promise<unknown>) => { if (!reason.trim()) { setError('El motivo es obligatorio.'); return; } setBusy(true); setError(''); try { await action(); setOrganization(await administrationService.organization()); } catch (failure) { setError(failure instanceof Error ? failure.message : 'No fue posible actualizar el usuario.'); } finally { setBusy(false); } };
  if (mode === 'list') return <><PageHeader eyebrow="USUARIOS" title="Administración de Usuarios" description="Identidades, roles y estados visibles dentro de la empresa autorizada." action={<Link className="primary" to="/usuarios/nuevo">Crear usuario</Link>} />{error && <div className="error">{error}</div>}<section className="table-wrap payroll-wide"><table><thead><tr><th>Código</th><th>Nombre</th><th>Rol</th><th>Sucursal</th><th>Departamento</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{organization.profiles.map((item) => { const role = organization.roles.find((entry) => entry.id === item.role_id); return <tr key={item.id}><td>{item.id.slice(0, 8)}</td><td>{item.full_name}</td><td>{roleLabel(role?.code)}</td><td>{organization.branches.find((entry) => entry.id === item.branch_id)?.name ?? '—'}</td><td>{organization.departments.find((entry) => entry.id === item.department_id)?.name ?? '—'}</td><td><Badge tone={item.status === 'active' ? 'green' : 'gray'}>{item.status}</Badge></td><td><div className="button-row"><Link className="secondary" to={`/usuarios/${item.id}`}>Ver</Link><Link className="secondary" to={`/usuarios/${item.id}/editar`}>Editar</Link></div></td></tr>; })}</tbody></table>{!organization.profiles.length && <Empty text="No hay usuarios visibles en este alcance." />}</section></>;
  if (!profile) return <Empty text="Usuario no encontrado o fuera del alcance autorizado." />;
  return <><PageHeader eyebrow="USUARIOS" title={mode === 'audit' ? 'Auditoría de usuario' : mode === 'edit' ? 'Editar usuario' : 'Usuario'} description={profile.full_name} action={<Link className="secondary" to="/usuarios">Volver</Link>} />{error && <div className="error">{error}</div>}{mode === 'edit' ? <section className="panel admin-form"><h2>Asignación administrativa</h2><label>Rol<select defaultValue={profile.role_id} onChange={(event) => void save(() => administrationService.updateUserRole(profile.id, event.target.value, reason))}>{organization.roles.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{roleLabel(item.code)}</option>)}</select></label><label>Estado<select defaultValue={profile.status} onChange={(event) => void save(() => administrationService.updateUserStatus(profile.id, event.target.value, reason))}><option value="active">Activo</option><option value="inactive">Inactivo</option><option value="suspended">Suspendido</option></select></label><label>Motivo<input value={reason} onChange={(event) => setReason(event.target.value)} required /></label><div className="button-row"><button className="secondary" disabled={busy} onClick={() => void save(() => administrationService.updateUserStatus(profile.id, profile.status === 'active' ? 'inactive' : 'active', reason))}>{profile.status === 'active' ? 'Desactivar usuario' : 'Activar usuario'}</button><button className="secondary" disabled={busy} onClick={() => { const email = window.prompt('Correo del usuario para enviar el restablecimiento de contraseña'); if (email) void authService.requestPasswordReset(email); }}>Restablecer contraseña</button></div><p>Empresa, sucursal, departamento, supervisor y permisos especiales se muestran en detalle. Su actualización requiere un RPC administrativo específico para conservar la auditoría de servidor.</p></section> : mode === 'audit' ? <UserAudit profileId={profile.id} /> : <><UserDetail profile={profile} organization={organization} /><div className="button-row"><Link className="primary" to={`/usuarios/${profile.id}/editar`}>Editar</Link><Link className="secondary" to={`/usuarios/${profile.id}/auditoria`}>Ver auditoría</Link></div></>}</>;
}
