import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {Empty,PageHeader} from '../components/UI';
import {downloadFinalExcel,downloadPayrollPdf} from '../modules/payroll/payrollExports';
import {payrollService,type PayrollPeriod,type PayrollSnapshot} from '../modules/payroll/payrollService';
const money=(n:number|undefined)=>`RD$ ${Number(n??0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
function usePayroll(){const[periods,setPeriods]=useState<PayrollPeriod[]>([]),[snapshot,setSnapshot]=useState<PayrollSnapshot|null>(null),[error,setError]=useState('');useEffect(()=>{void(async()=>{try{const p=await payrollService.listPeriods();setPeriods(p);if(p[0])setSnapshot(await payrollService.get(p[0].id))}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar nómina.')}})()},[]);return{periods,snapshot,setSnapshot,error}}
export function PayrollClosurePage(){const{snapshot,setSnapshot,error}=usePayroll();const[notes,setNotes]=useState('');async function close(){if(!snapshot)return;if(snapshot.nomina.desactualizada||snapshot.nomina.errores.length||!snapshot.detalles.length)return;await payrollService.changeState(snapshot.periodo.id,'CERRADA',notes||'Cierre de nómina');setSnapshot(await payrollService.get(snapshot.periodo.id));}if(!snapshot)return <Empty text={error||'No hay nómina calculada.'}/>;const s=snapshot.nomina.resumen;const blocked=snapshot.nomina.desactualizada||!!snapshot.nomina.errores.length||!snapshot.detalles.length||snapshot.periodo.estado!=='APROBADA';return <><PageHeader eyebrow="NOMINA" title="Cierre de nómina" description="Cierre irreversible y auditado." action={<Link className="secondary" to="/nomina">Volver</Link>}/><section className="panel"><p>Período: {snapshot.periodo.fecha_inicio} — {snapshot.periodo.fecha_fin} · Estado: <b>{snapshot.periodo.estado}</b></p><div className="stats payroll-stats">{[['Empleados',s.empleados],['Total salarios',money(s.total_sueldos)],['Horas extras',money(s.total_horas_extras)],['Días festivos',money(0)],['Préstamos',money(s.total_prestamos)],['Créditos',money(s.total_creditos)],['AFP + SFS',money(s.total_impuestos)],['Otros descuentos',money(s.total_otros_descuentos)],['Total neto',money(s.total_general_pagado)]].map(([k,v])=><article className="stat" key={String(k)}><span>{k}</span><strong>{v??0}</strong></article>)}</div><label>Observaciones<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><div className="button-row"><button className="secondary" disabled={snapshot.periodo.estado==='CERRADA'} onClick={()=>void payrollService.calculate(snapshot.periodo.id)}>Generar Nómina</button><button className="primary" disabled={blocked} onClick={()=>void close()}>Cerrar Nómina</button></div>{blocked&&snapshot.periodo.estado!=='CERRADA'&&<p className="error">No se puede cerrar: debe estar aprobada, calculada sin errores, sin revisiones pendientes y con empleados calculados.</p>}</section></>}
export function PayrollHistoryPage(){const{periods,snapshot,error}=usePayroll();const periodName=snapshot?`nomina-${snapshot.periodo.fecha_inicio}-${snapshot.periodo.fecha_fin}`:'nomina';return <><PageHeader eyebrow="NOMINA" title="Historial" description="Períodos, cambios y exportaciones." action={<Link className="secondary" to="/nomina">Volver</Link>}/>{error&&<div className="error">{error}</div>}<section className="table-wrap"><table><thead><tr><th>Período</th><th>Usuario</th><th>Fecha</th><th>Estado</th><th>Total pagado</th></tr></thead><tbody>{periods.map(p=><tr key={p.id}><td>{p.fecha_inicio} — {p.fecha_fin}</td><td>{snapshot?.auditoria[0]?.empleado_id??'Registrado en auditoría'}</td><td>{snapshot?.auditoria[0]?.fecha?new Date(snapshot.auditoria[0].fecha).toLocaleString():'—'}</td><td>{p.estado}</td><td>{money(p.resumen?.total_general_pagado)}</td></tr>)}</tbody></table></section>{snapshot&&<section className="panel"><h2>Detalle del período</h2><p>Empleados: {snapshot.detalles.length} · Ganancias: {money(snapshot.nomina.resumen.total_general_pagado)} · Observaciones y cambios: {snapshot.auditoria.map(a=>a.accion).join(', ')||'Sin cambios.'}</p><div className="button-row"><button className="secondary" onClick={()=>void downloadFinalExcel(snapshot,`${periodName}.xlsx`)}>Exportar Excel</button><button className="secondary" onClick={()=>void downloadPayrollPdf(snapshot,'CONTROLHORARIO',`${periodName}.pdf`)}>Exportar PDF</button></div></section>}</>}
