import {useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import {Empty,PageHeader} from '../components/UI';
import {payrollService,type PayrollDetail,type PayrollEmployee,type PayrollSnapshot} from '../modules/payroll/payrollService';

const money=(n:number)=>`RD$ ${Number(n||0).toLocaleString('es-DO',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
export function PayrollPaymentsPage(){
 const [employees,setEmployees]=useState<PayrollEmployee[]>([]),[data,setData]=useState<PayrollSnapshot|null>(null),[open,setOpen]=useState(''),[notes,setNotes]=useState<Record<string,string>>({}),[error,setError]=useState('');
 useEffect(()=>{void(async()=>{try{const periods=await payrollService.listPeriods();const id=periods[0]?.id;if(!id)return;const [people,snapshot]=await Promise.all([payrollService.listEmployees(),payrollService.get(id)]);setEmployees(people.sort((a,b)=>a.codigo.localeCompare(b.codigo)));setData(snapshot)}catch(e){setError(e instanceof Error?e.message:'No fue posible cargar pagos.')}})()},[]);
 const rows=useMemo(()=>[...(data?.detalles??[])].sort((a,b)=>a.codigo_empleado.localeCompare(b.codigo_empleado)),[data]);
 const loan=(employeeId:string)=>data?.prestamos.find(x=>x.empleado_id===employeeId&&x.estado==='ENTREGADO');
 const advance=async()=>{if(!data)return;const next:{[key:string]:'EN_REVISION'|'APROBADA'|'CERRADA'}={CALCULADA:'EN_REVISION',EN_REVISION:'APROBADA',APROBADA:'CERRADA'};const state=next[data.periodo.estado];if(!state)return;await payrollService.changeState(data.periodo.id,state,'Avance desde pagos');setData(await payrollService.get(data.periodo.id));};
 const print=(detail:PayrollDetail)=>{const doc=new jsPDF();doc.text('CONTROLHORARIO · Volante de pago',14,16);doc.text(`${detail.nombre_empleado} · ${detail.codigo_empleado}`,14,25);autoTable(doc,{startY:32,head:[['Concepto','Monto']],body:[['Sueldo bruto',money(detail.bruto)],['Horas extras',money(detail.total_horas_extras)],['AFP',money(detail.afp)],['SFS',money(detail.sfs)],['Préstamo',money(detail.descuento_prestamo)],['Crédito',money(detail.descuento_credito)],['Otros',money(detail.otros_descuentos+detail.rotura_falta+detail.descuento_fijo)],['Total a pagar',money(detail.neto)],['Observaciones',notes[detail.id]??'']]});doc.save(`volante-${detail.codigo_empleado}.pdf`)};
 return <><PageHeader eyebrow="NOMINA" title="Pagos" description="Pagos calculados desde ganancias y descuentos ya consolidados." action={<div className="button-row"><Link className="secondary" to="/nomina">Volver</Link><button className="secondary" onClick={()=>rows.forEach(print)}>Imprimir todos los volantes</button>{data&&(['CALCULADA','EN_REVISION','APROBADA'].includes(data.periodo.estado))&&<button className="primary" onClick={()=>void advance()}>Avanzar a siguiente estado</button>}</div>}/>{error&&<div className="error">{error}</div>}{!data?<Empty text="No existe una nómina calculada."/>:<section className="table-wrap payroll-wide"><table><thead><tr><th>Código</th><th>Nombre</th><th>Sueldo Bruto</th><th>Día Festivo</th><th>H/Extras</th><th>AFP + SFS</th><th>Desc. Préstamo</th><th>Pend. Préstamo</th><th>Desc. Crédito</th><th>Otros</th><th>Total a Pagar</th><th>Abrir/Cerrar</th><th>Imprimir Volante</th></tr></thead><tbody>{rows.map(d=>{const l=loan(d.empleado_id),expanded=open===d.id,total=Math.max(0,d.bruto+d.total_horas_extras-d.afp-d.sfs-d.descuento_prestamo-d.descuento_credito-d.otros_descuentos-d.rotura_falta-d.descuento_fijo);return <><tr key={d.id}><td>{d.codigo_empleado}</td><td>{d.nombre_empleado}</td><td>{money(d.bruto)}</td><td>{money(0)}</td><td>{money(d.total_horas_extras)}</td><td>{money(d.afp+d.sfs)}</td><td>{money(d.descuento_prestamo)}</td><td>{money(l?.pendiente??0)}</td><td>{money(d.descuento_credito)}</td><td>{money(d.otros_descuentos+d.rotura_falta+d.descuento_fijo)}</td><td><b>{money(total)}</b></td><td><button className="secondary" onClick={()=>setOpen(expanded?'':d.id)}>{expanded?'Cerrar':'Abrir'}</button></td><td><button className="secondary" onClick={()=>print(d)}>Imprimir</button></td></tr>{expanded&&<tr className="payroll-slip" key={`${d.id}-open`}><td colSpan={13}><b>Salario base:</b> {money(d.sueldo_base)} · <b>Horas normales:</b> {d.horas_normales} · <b>Extras:</b> {d.horas_extras} · <b>Festivo:</b> {money(0)} · <b>AFP:</b> {money(d.afp)} · <b>SFS:</b> {money(d.sfs)} · <b>Ganancias acumuladas:</b> {money(d.pago_normal+d.total_horas_extras)}<br/><label>Observaciones<textarea value={notes[d.id]??''} onChange={e=>setNotes(v=>({...v,[d.id]:e.target.value}))}/></label><p>Historial: {data.auditoria.filter(a=>a.empleado_id===d.empleado_id).map(a=>`${a.accion} ${new Date(a.fecha).toLocaleString()}`).join(' · ')||'Sin cambios.'}</p></td></tr>}</>})}</tbody></table></section>}</>;
}
